var youtubeBase="http://www.youtube.com/watch?v=",vimeoBase="http://vimeo.com/",soundCloudBase="http://soundcloud.com/",imageBase=/http?:\/\/([/|.|\w%'-|\s])*\.(?:jpg|gif|png)/gim,soundBase=/http?:\/\/([/|.|\w'-|\s])*\.(?:mp3|ogg|wav)/gim,linkBase0=/(\b(https?|ftp):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim,linkBase1=/(^|[^\/])(www\.[\S]+(\b|$))/gim,mp3Player='<object type="application/x-shockwave-flash" data="http://flash-mp3-player.net/medias/player_mp3_maxi.swf" width="12" height="12"><param name="movie" value="http://flash-mp3-player.net/medias/player_mp3_maxi.swf" /><param name="bgcolor" value="#e5edef" /><param name="FlashVars" value="mp3={url}&amp;width=12&amp;height=12&amp;showslider=0&amp;showloading=never&amp;buttonwidth=12&amp;sliderwidth=0&amp;sliderheight=0&amp;volumewidth=0&amp;volumeheight=0&amp;loadingcolor=ffffff&amp;bgcolor=e5edef&amp;bgcolor1=e5edef&amp;bgcolor2=e5edef&amp;slidercolor1=ffffff&amp;slidercolor2=ffffff&amp;sliderovercolor=ffffff&amp;buttoncolor=304e63&amp;buttonovercolor=505050" /></object>',
linkPlayer='<div class="link-icon-cover"><a href={url} target="_blank">L</a></div>';
function common_checkEmail(a){var b=a.indexOf("@"),c=a.length;if(/^([A-Za-z0-9_\-\.])+\@([A-Za-z0-9_\-\.])+\.([A-Za-z]{2,4})$/.test(a)==false)return false;if(a.indexOf("@")==-1)return false;if(a.indexOf("@")==-1||a.indexOf("@")==0||a.indexOf("@")==c)return false;if(a.indexOf(".")==-1||a.indexOf(".")==0||a.indexOf(".")==c)return false;if(a.indexOf("@",b+1)!=-1)return false;if(a.substring(b-1,b)=="."||a.substring(b+1,b+2)==".")return false;if(a.indexOf(".",b+2)==-1)return false;if(a.indexOf(" ")!=-1)return false;
return true}function common_checkPassword(a){var b=a.length;if(b<6||b>15)return false;if(/^([a-zA-Z0-9_])+$/.test(a)==false)return false;return true}function common_daysBetween(a,b){var c=a.getTime(),d=b.getTime();return Math.round(Math.abs(c-d)/864E5)}function common_incrementAskQuestionCount(){var a=parseInt(cookie_get(COOKIE_QUESTION_ASKED));a++;$.cookie(COOKIE_QUESTION_ASKED,a)}
function common_incrementLoveQuestionCount(){var a=parseInt(cookie_get(COOKIE_QUESTION_FAVED));a++;$.cookie(COOKIE_QUESTION_FAVED,a)}function common_decrementLoveQuestionCount(){var a=parseInt(cookie_get(COOKIE_QUESTION_FAVED));a--;$.cookie(COOKIE_QUESTION_FAVED,a)}function common_incrementAnswerQuestionCount(){var a=parseInt(cookie_get(COOKIE_QUESTION_ANSWERED));a++;$.cookie(COOKIE_QUESTION_ANSWERED,a)}
function common_getRemainingTime(a){if(a>2E12)a/=1E3;if(a<1397458597)a*=1E3;a=new Date-a;if(a.valueOf()>0){var b=a.valueOf()/1E3;a=Math.floor(b/86400)%86400;var c=Math.floor(b/3600)%24,d=Math.floor(b/60)%60;b=Math.floor(b/1)%60;if(a>0)return a+" days ago";else if(c>0)return c+" hours ago";else if(d>0)return d+" minutes ago";else if(b>0)return b+" seconds ago"}else return"now"}var common_MoreFunction=null;
function common_registerMoreActionListener(a){common_MoreFunction=a;$(window).scroll(function(){$(window).scrollTop()+100>=$(document).height()-$(window).height()&&common_MoreFunction!=null&&common_MoreFunction()})}function common_newOption(a,b){return"<option value="+b+">"+a+"</option>"}function common_getURLSegment(a){return jQuery.url.segment(a)}
function common_contentProcessing(a,b){var c=a.indexOf(youtubeBase),d=a.indexOf(vimeoBase),e=a.indexOf(soundCloudBase),h=a.match(imageBase),g=b!=CONTENT_PROCESS_FOR_ONE_QUESTION,f="";a=common_htmlStrip(a);f=c!=-1?common_embedYouTubeVideo(a,c,g):d!=-1?common_embedVimeoVideo(a,d,g):e!=-1?common_embedSoundCloudAudio(a,e,g):h!=null?common_embedImage(a,h[0],g):"";if(b==CONTENT_PROCESS_FOR_ONE_QUESTION)f=f==""?common_linkify(a):common_linkify2(f);return f}
function common_contentProcess(a){a=common_htmlStrip(a);return common_linkify(a)}function common_isContainsMedia(a){return common_isContainsVimeoVideo(a)||common_isContainsYouTubeVideo(a)||common_isContainsImage(a)||common_isContainsSoundCloud(a)}function common_isContainsImage(a){return a.match(imageBase)!=null}function common_isContainsSound(a){return a.match(soundBase)!=null}function common_isContainsYouTubeVideo(a){return a.indexOf(youtubeBase)!=-1}
function common_isContainsVimeoVideo(a){return a.indexOf(vimeoBase)!=-1}function common_isContainsSoundCloud(a){return a.indexOf(soundCloudBase)!=-1}function common_isContainsLink0(a){return a.match(linkBase0)!=null}function common_isContainsLink1(a){return a.match(linkBase1)!=null}var common_stripHTMLDIV=$('<div class="stripHTMLClass">text</div>');function common_htmlStrip(a){return common_stripHTMLDIV.text(a).html()}function common_preventScreenFlash(){$("#divBody").show()}
function common_linkify(a){return a.replace(/(\b(https?|ftp):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/gim,'<a href="$1" target="_blank">$1</a>').replace(/(^|[^\/])(www\.[\S]+(\b|$))/gim,'$1<a href="http://$2" target="_blank">$2</a>').replace(/@(\w+)/gim,'@<a href="http://trendocean.com/$1" target="_blank">$1</a>').replace(/#(\w+)/gim,'#<a href="http://trendocean.com/search.html#quendies=$1" target="_blank">$1</a>')}
function common_linkify2(a){return a.replace(/@(\w+)/gim,'@<a href="http://trendocean.com/$1" target="_blank">$1</a>').replace(/#(\w+)/gim,'#<a href="http://trendocean.com/search.html#quendies=$1" target="_blank">$1</a>')}function common_linkifyNotification(a,b){var c=a.replace(/@(\w+)/gim,'@<a href="http://trendocean.com/$1">$1</a>').replace(/\u00e9(\w+)/gim,'<a href="http://trendocean.com/question/$1">$qText</a>');return c=c.replace("$qText",b)}
function common_embedYouTubeVideo(a,b,c){start=b+youtubeBase.length;end=a.length;if(a.indexOf("&",start)!=-1){end0=a.indexOf("&",start);if(end0<end)end=end0}if(a.indexOf("#",start)!=-1){end1=a.indexOf("#",start);if(end1<end)end=end1}if(a.indexOf(" ",start)!=-1){end2=a.indexOf(" ",start);if(end2<end)end=end2}endReal=a.length;if(a.indexOf(" ",start)!=-1)endReal=a.indexOf(" ",start);allyoutube=a.substring(b,endReal);code=a.substring(start,end);b=youtube.replace("$youtubecode$",code);if(c)return b;return a.replace(allyoutube,
b)}function common_embedVimeoVideo(a,b,c){start=b+vimeoBase.length;end=a.length;if(a.indexOf(" ",start)!=-1)end=a.indexOf(" ",start);endReal=a.length;if(a.indexOf(" ",start)!=-1)endReal=a.indexOf(" ",start);allvimeo=a.substring(b,endReal);code=a.substring(start,end);b=vimeo.replace("$vimeocode$",code);return c?b:a.replace(allvimeo,b)}
function common_embedSoundCloudAudio(a,b,c){start=b+soundCloudBase.length;endReal=a.length;if(a.indexOf(" ",start)!=-1)endReal=a.indexOf(" ",start);allsoundCloud=a.substring(b,endReal);jQuery.url.setUrl(allsoundCloud);code1=jQuery.url.segment(0);code2=jQuery.url.segment(1);b=soundCloud.replace("$soundcloudCode1$",code1);b=b.replace("$soundcloudCode2$",code2);b=b.replace("$soundcloudCode3$",code1);b=b.replace("$soundcloudCode4$",code2);return c?b:a.replace(allsoundCloud,b)}
function common_embedImage(a,b,c){var d=htmlImgURL.replace("{url}",b);return c?d:a.replace(b,d)}
function common_checkPOST(){var a=false;if(cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL)notifyBar_display(ERR_MSG_PLEASE_SIGNIN,ICON_URL_NOTIFY_WRONG);else if(cookie_get(COOKIE_ACTIVATED)!="ACTIVATED")$.ajax({url:"api/users/"+cookie_get(COOKIE_USERNAME),type:"GET",async:false,success:function(b){if(b.accountState=="ACTIVATED"){cookie_wrap(COOKIE_ACTIVATED,b.accountState);a=true}else notifyBar_display(INFO_MSG_REGISTRATION_OK,ICON_URL_NOTIFY_WRONG)},error:function(){notifyBar_display(INFO_MSG_REGISTRATION_OK,
ICON_URL_NOTIFY_WRONG)}});else a=true;return a}function common_checkAnswerPOST(){return true}function common_checkActivated(){if(cookie_get(COOKIE_ACTIVATED)!="ACTIVATED")return false;return true}function common_choiceProcess(a){var b=a.match(soundBase),c=a.match(linkBase0),d=a.match(linkBase1);return b!=null?a.replace(b[0],""):c!=null?a.replace(c[0],""):d!=null?a.replace(d[0],""):a}
function common_choiceBoxProcess(a){var b=a.match(soundBase),c=a.match(linkBase0);a=a.match(linkBase1);return b!=null?mp3Player.replace("{url}",b[0]):c!=null?linkPlayer.replace("{url}",c[0]):a!=null?linkPlayer.replace("{url}",a[0]):""}function common_choiceBoxProcessOneQuestion(a,b){var c=a.match(soundBase),d=a.match(linkBase0),e=a.match(linkBase1);return c!=null?b.replace("{url}",c[0]):d!=null?linkPlayer.replace("{url}",d[0]):e!=null?linkPlayer.replace("{url}",e[0]):""}
function common_contentCounterProcess(a){var b=a.match(soundBase),c=a.match(linkBase0),d=a.match(linkBase1);return b!=null?a.replace(b[0],""):c!=null?a.replace(c[0],""):d!=null?a.replace(d[0],""):a};
