var HTTP_STATUS_OK=200,HTTP_STATUS_NOT_MODIFIED=304,HTTP_STATUS_BAD_REQUEST=400,HTTP_STATUS_UNAUTHORIZED=401,HTTP_STATUS_FORBIDDEN=403,HTTP_STATUS_NOT_FOUND=404,HTTP_STATUS_NOT_ACCAtblPodcasts=406,HTTP_STATUS_ENHANCE_YOUR_CALM=420,HTTP_STATUS_INTERNAL_SERVER_ERROR=500,HTTP_STATUS_BAD_GATEWAY=500,HTTP_STATUS_SERVICE_UNAVAILABLE=503,CONTENT_PROCESS_FOR_ASKED_QUESTION_PREVIEW=0,CONTENT_PROCESS_FOR_QUESTION_TABLE=1,CONTENT_PROCESS_FOR_ONE_QUESTION=2,CONTENT_PROCESS_FOR_COMMENT=2,API_PROFILE_MYQUESTIONS=
"api/questions/byuser/",API_PROFILE_ANSWEREDS="api/questions/answered/",API_PROFILE_FAVS="api/favorites/",API_PROFILE_COFFEES="api/messages/public/",COOKIE_REDIRECTION_SRC="redirection_source",COOKIE_REDIRECTION_PAGE="redirection_page",COOKIE_REDIRECTION_MSG="redirection_msg",COOKIE_REDIRECTION_ICON="redirection_icon",COOKIE_SEARCH_CONTENT="searchContent",COOKIE_ABOUT="about",COOKIE_ACOUNT_STATE="acountstate",COOKIE_BIRTH="birthday",COOKIE_BG_TILED="background_tiled",COOKIE_BG_URL="background_url",
COOKIE_BG_COLOR="background_color",COOKIE_CITY="city",COOKIE_CITY_ID="city_id",COOKIE_COUNTRY="country",COOKIE_COUNTRY_CODE="country_code",COOKIE_EDUCATION="education",COOKIE_EMAIL="email",COOKIE_FALLOWED_COUNT="fallowed_count",COOKIE_FALLOWER_COUNT="fallower_count",COOKIE_AVATAR_SMALL_URL="avatar_small_url",COOKIE_AVATAR_LARGE_URL="avatar_large_url",COOKIE_FULLNAME="fullname",COOKIE_GENDER="gender",COOKIE_LANGUAGE="language",COOKIE_MARGINAL="marginal",COOKIE_QUESTION_ANSWERED="question_answered",
COOKIE_QUESTION_ASKED="question_asked",COOKIE_QUESTION_FAVED="question_faved",COOKIE_USERQUESTIONS_FAVED="userquestions_faved",COOKIE_THEME_NAME="theme_name",COOKIE_ANSWER_VISB="answer_visibility",COOKIE_EMAIL_VISB="email_visibility",COOKIE_PROFILE_VISB="profile_visibility",COOKIE_NOTFY_WHENFRIENDASKEDQUESTION="notify_whenfriendaskedquestion",COOKIE_NOTFY_WHENMYQUESTIONARELOVED="notify_whenmyquestionareloved",COOKIE_NOTFY_WHENMYQUESTIONARECOMMENTED="notify_whenmyquestionarecommented",COOKIE_NOTFY_WHENMYQUESTIONAREFLAGGED=
"notify_whenmyquestionareflagged",COOKIE_NOTFY_WHENSOMEBODYFOLLOWSME="notify_whensomebodyfollowsme",COOKIE_NOTFY_WHENSOMEBODYSENDCOFFEE="notifyWhenSomebodySendACoffe",COOKIE_CAPABILITY_OF_HASLIVEPLAYER="capability_of_hasliveplayer",COOKIE_CAPABILITY_OF_LIVEPLAYERSOURCE="capability_of_liveplayersource",COOKIE_CAPABILITY_OF_LIVEPLAYERSLOGAN="capability_of_liveplayerslogan",COOKIE_CAPABILITY_OF_HASPODCASTTAB="capability_of_haspodcasttab",COOKIE_CAPABILITY_OF_PODCAST0_TITLE="capability_of_podcast0_title",
COOKIE_CAPABILITY_OF_PODCAST0_URL="capability_of_podcast0_url",COOKIE_CAPABILITY_OF_PODCAST1_TITLE="capability_of_podcast1_title",COOKIE_CAPABILITY_OF_PODCAST1_URL="capability_of_podcast1_url",COOKIE_CAPABILITY_OF_PODCAST2_TITLE="capability_of_podcast2_title",COOKIE_CAPABILITY_OF_PODCAST2_URL="capability_of_podcast2_url",COOKIE_CAPABILITY_OF_PODCAST3_TITLE="capability_of_podcast3_title",COOKIE_CAPABILITY_OF_PODCAST3_URL="capability_of_podcast3_url",COOKIE_CAPABILITY_OF_PODCAST4_TITLE="capability_of_podcast4_title",
COOKIE_CAPABILITY_OF_PODCAST4_URL="capability_of_podcast4_url",COOKIE_CAPABILITY_OF_PODCAST5_TITLE="capability_of_podcast5_title",COOKIE_CAPABILITY_OF_PODCAST5_URL="capability_of_podcast5_url",COOKIE_CAPABILITY_OF_PODCAST6_TITLE="capability_of_podcast6_title",COOKIE_CAPABILITY_OF_PODCAST6_URL="capability_of_podcast6_url",COOKIE_CAPABILITY_OF_PODCAST7_TITLE="capability_of_podcast7_title",COOKIE_CAPABILITY_OF_PODCAST7_URL="capability_of_podcast7_url",COOKIE_CAPABILITY_OF_TABVISB="capability_of_tabvisb",
COOKIE_CAPABILITY_OF_ASKED_TAB_VISB="capability_of_askedtabvisb",COOKIE_CAPABILITY_OF_ANSWERED_TAB_VISB="capability_of_answredtabvisb",COOKIE_CAPABILITY_OF_LOVED_TAB_VISB="capability_of_lovedtabvisb",COOKIE_CAPABILITY_OF_DROPS_TAB_VISB="capability_of_dropstabvisb",COOKIE_CAPABILITY_OF_COFFEES_TAB_VISB="capability_of_coffeestabvisb",COOKIE_CAPABILITY_OF_PODCAST_TAB_VISB="capability_of_podcasttabvisb",COOKIE_SCORE="score",COOKIE_SIGNIN="signin",COOKIE_ACTIVATED="accountState",COOKIE_REMEMBERME="rememberMe",
COOKIE_USERNAME="username",COOKIE_LOGINUSER_TREND="loginUser_Trend",COOKIE_SIGNIN_VAL="OK",COOKIE_ASKQUICK_QBODY="askquick_qbody",DATA_CHOICE_INDEX="index",UPDATE_CLIENT_LASTTIME=5E3,UPDATE_DELAY_MYCOFFEE=6E4,UPDATE_DELAY_INBOX=6E4,UPDATE_DELAY_OUTBOX=6E4,UPDATE_MAINBAR_SCORE=18E4,UPDATE_MAINBAR_NOTIFICATIONCOUNTS=6E4,COFFEE_DLG_HIDE_WAIT_TIME=1E3,MSG_DLG_HIDE_WAIT_TIME=1E3,PAGE_INDEX="index.html",PAGE_CHANGEPASSWD="changePassword.html",PAGE_ACCOUNT="account.html",PAGE_PASSWD="password.html",PAGE_DESIGN=
"design.html",PAGE_NOTIFICATIONS="notifications.html",PAGE_ASKQUESTION="askquestion.html",PAGE_REGISTER="register.html",PAGE_HOME="home.html",PAGE_PROFILE="profile.html",PAGE_LOGIN="login.html",PAGE_RESEND_PASSWD="resend_password",PAGE_ONEQUESTION="onequestion.xhtml",PAGE_MSGBOX="messages.html",PAGE_FALLOWS="people.html",PAGE_SEARCH="search.html",PAGE_RECOMMEND="recommend.html",PAGE_INVITE="invite.html",PAGE_FINDFRIENDS="trendradar.html",PAGE_NEWFOLLOWERS="newfollowers.html",PAGE_ABOUT="about.html",
PAGE_BLOG="blog.html",PAGE_TEAM="team.html",PAGE_HELP="help.html",PAGE_TERMS="terms.html",PAGE_COMMINGSOON="comingsoon.html",PAGE_OVERLOAD="overload.html",PAGE_ERROR="error.html",PAGE_OPPS="opss.html",ANCHOR_ANSWERED="#answered",ANCHOR_LOVED="#loved",ANCHOR_MYQUESTIONS="#myquestions",ANCHOR_MYCOFFEE="#mycoffee",ANCHOR_PODCAST="#podcast",ANCHOR_DROPS="#drops",ANCHOR_FOLLOWERS="#followers",ANCHOR_FOLLOWEDS="#following",ANCHOR_PEOPLE="#people",ANCHOR_QUENDIES="#quendies",ANCHOR_INBOX="#inbox",ANCHOR_SENT=
"#sent",ANCHOR_INVITE="#invite",ANCHOR_RECOMMEND="#recommend",QNODE_BTN_INVALID="invalid",QNODE_BTN_ANSWER="answer",QNODE_BTN_CLOSE="close",QNODE_BTN_OPENSTATS="open stats",QUESTION_TOTAL_ANSWERED_INDEX=116,THEME_NAME_DEFAULT="default",THEME_NAME_MARGINAL="marginal",THEME_NAME_BEACH="beach",THEME_NAME_WHALE="whale",THEME_NAME_RADIOODTU="radioodtu",VISB_EVERYONE="EVERYONE",VISB_ONLY_FRIENDS="ONLY_FRIENDS",VISB_ONLY_ME="ONLY_ME",QACTIONS_FAVED="Question Faved",QACTIONS_UNFAVED="Question UnFaved",QACTIONS_ANSWERED=
"Question Answered",QUESTIONS_IN_PROMOTED="QuestionsPromoted",QUESTIONS_IN_FOLLOW="QuestionsInFollow",QUESTIONS_IN_LATEST="QuestionsInLatest",QUESTIONS_IN_TRENDS="QuestionsInTrends",QUESTIONS_IN_TRENDS_TYPE="trends",QUESTIONS_IN_TODAY="today",QUESTIONS_IN_WEEK="week",QUESTIONS_IN_MONTH="month",QUESTIONS_IN_YEAR="year",MAINBAR_LINK_SETTING="settings",MAINBAR_LINK_MYOCEAN="myocean",MAINBAR_LINK_PROFILE="profile",TEXT_NULL="",TEXT_TRUE="true",TEXT_FALSE="false",TEXT_SELECT="Select",TEXT_TRENDY="trendy",
TEXT_MARGINAL="eccentric",TEXT_MALE="Male",TEXT_MALE_BIG="MALE",TEXT_FEMALE="Female",TEXT_FEMALE_BIG="FEMALE",TEXT_FOLLOWERS="followers ",TEXT_FOLLOWEDS="following ",MAX_CHOICE_COUNT=10,INDEX_OF_NOT_ANSWERED="-1",ICON_URL_ERR="css/default/images/error.png",ICON_URL_OK="css/default/images/ok.png",ICON_URL_LOVE_UNSELECTED="css/default/images/lovee_unselected.png",ICON_URL_LOVE_SELECTED="css/default/images/lovee_selected.png",ICON_URL_NOTIFY_TRUE="notifyimage-true",ICON_URL_NOTIFY_WRONG="notifyimage-wrong",
KEY_ENTER="13",KEY_ESCAPE="27",ERR_MSG_WEBSERVICE="Web Service Error",ERR_MSG_NOT_ACTIVATED_ACCOUNT="Please Activate Acount At First",ERR_MSG_LOGIN_FAILED="Login Failed. Please Try Again",ERR_MSG_PLEASE_SIGNIN="Please signin",ERR_MSG_RESEND_PASSWD_FAILED="Wrong username/email",ERR_MSG_ALREADY_SIGNIN="You are already signin an account",ERR_MSG_QUESTION_CANT_SENDED="question sharing fails",ERR_MSG_USERNAME_INVALID_FORMAT="username is invalid",ERR_MSG_USERNAME_EXIST="username exist",ERR_MSG_EMAIL_INVALID_FORMAT=
"e-mail is invalid",ERR_MSG_EMAIL_EXIST="e-mail exist",ERR_MSG_PASSWD_INVALID_FORMAT="password is invalid",ERR_MSG_CAPTCHA_INVALID="captcha is invalid",ERR_MSG_BIRTH_INVALID="birth is invalid",ERR_MSG_UNCHECK_IAGREE_TERMS="uncheck i agree terms",ERR_MSG_USERNAME_EMPTY="username is empty",ERR_MSG_FULLNAME_EMPTY="fullname is empty",ERR_MSG_EMAIL_EMPTY="email is empty",ERR_MSG_PASSWD_EMPTY="passwd is empty",ERR_MSG_GENDER_EMPTY="gender is empty",ERR_MSG_COUNTRYANDCITY_EMPTY="country/city is empty",ERR_MSG_EDUCATION_EMPTY=
"education is empty",ERR_MSG_CAPTCHA_EMPTY="captcha is empty",ERR_MSG_QUESTION_NOT_ADDED="question not added",ERR_MSG_QUESTION_CHOICE_COUNT_INVALID="please enter two choices",ERR_MSG_QUESTION_BODY_MIN_LENGTH="question must be minimum 5 characters",ERR_MSG_QUESTION_BODY_MAX_LENGTH="question was over 140 characters",ERR_MSG_QUESTION_CHOICES_MAX_LENGTH="choice was over 40 characters",ERR_MSG_COMMENT_MAX_LENGTH="comment was over 300 characters",ERR_MSG_ACCOUNT_NOT_CHANGED="account not changed",ERR_MSG_NOT_IMPLEMENTED=
"Not Implemented Yet",INFO_MSG_OK="ok",INFO_MSG_QUESTION_ADDED="question added",INFO_MSG_QUESTION_SENDED="question shared with email",INFO_MSG_REGISTRATION_OK="check your e-mail and activate account",INFO_MSG_RESEND_PASSWD_OK="Password Send To Email",INFO_MSG_ACCOUNT_CHANGED="account changed",INFO_MSG_NOTIFICATIONS_CHANGED="notifications changed",INFO_COMING_NEXT_VERSION="Coming Next Version";
