var display_followers=null;
function followTab_renderFollowers(b,a,d,c){display_followers=c==null||c==TEXT_NULL?[]:$.isArray(c.user)?c.user:Array(c.user);$(b+"btnAll").attr("href","follow/"+followedTab_profileUserName+"#"+a);for(i=0;i<display_followers.length;i++){a=display_followers[i];c="<a href=fallowerLink  title='fallowerFullName'><img src=fallowerImg class=profile-follow-rounded width=30 height=30/></a>".replace("fallowerImg",a.smallAvatarURL);c=c.replace("fallowerLink",a.username);c=c.replace("fallowerFullName",a.fullName);
$(b+i).html(c)}for(i=display_followers.length;i<d;i++)$(b+i).html("<img src=css/default/images/sampleavatar.png  width=30 height=30/>")}var loginedUserFolloweds=null,followButton=null,followedTab_profileUserName=null;
function followTab_fillFollowers(b){$.ajax({url:"api/users/follower/"+followedTab_profileUserName,type:"GET",success:function(a){followTab_renderFollowers("#follower_","followers",b,a)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG);return false}});return false}
function followTab_fillFolloweds(b){$.ajax({url:"api/users/followed/"+followedTab_profileUserName,type:"GET",success:function(a){followTab_renderFollowers("#following_","following",b,a)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG);return false}});return false}
function followTab_updateLoginUserFolloweds(){if(cookie_get(COOKIE_SIGNIN)==COOKIE_SIGNIN_VAL){var b=cookie_get(COOKIE_USERNAME);$.ajax({url:"api/users/followed/"+b,type:"GET",success:function(a){loginedUserFolloweds=a==null?[]:$.isArray(a.user)?a.user:Array(a.user);followTab_followBtn_updateStatus()},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG);return false}});return false}}
function followTab_fallowBtn_initialize(b){followButton=b;b.click(function(a){a.preventDefault();if(common_checkPOST()){a=null;a=profile_isVisibleToLoginUser()?profileFollowing==TEXT_FALSE?"POST":"DELETE":"POST";$.ajax({url:"api/users/follow/"+followedTab_profileUserName,type:a,success:function(){if(profile_isVisibleToLoginUser()){profileFollowing=profileFollowing==TEXT_FALSE?TEXT_TRUE:TEXT_FALSE;profile_updateProfile()}else notifyBar_display("Follow Request Sended",ICON_URL_NOTIFY_TRUE)},error:function(d){notifyBar_display(ERR_MSG_WEBSERVICE+
":"+d.status,ICON_URL_NOTIFY_WRONG);return false}});return false}});followTab_updateLoginUserFolloweds()}function followTab_followBtn_updateStatus(){followButton.removeClass();if(profile_isVisibleToLoginUser())if(profileFollowing==TEXT_FALSE){followButton.addClass("follow_request");followButton.html("follow")}else{followButton.addClass("follow_request_remove");followButton.html("unfollow")}else{followButton.addClass("follow_request");followButton.html("follow request")}}
function followTab_followBtn_setContent(){cookie_get(COOKIE_USERNAME)==followedTab_profileUserName?followButton.hide():followButton.show();followTab_followBtn_updateStatus()}function followTab_setContent(b){followedTab_profileUserName=b};
