var mainBarScoreUpdater=null,mainBarNotificationCountsUpdater=null,mainBarRP="";
function mainBar_refreshInfo(){var a=cookie_get(COOKIE_USERNAME),b=cookie_get(COOKIE_FULLNAME),c=cookie_get(COOKIE_LOGINUSER_TREND),e=TEXT_TRENDY,d=0;if(cookie_get(COOKIE_MARGINAL)==TEXT_TRUE){e=TEXT_MARGINAL;d=100-parseInt(parseFloat(c)*100)}else d=parseInt(parseFloat(c)*100);$("#labelMe_MainBar").text(b+", "+d+"% "+e);$("#username_MainBar").text(a);cookie_get(COOKIE_PROFILE_VISB)==TEXT_TRUE?$("#friends_MainBar").hide():$("#friends_MainBar").show()}
function mainBar_initialize(a){mainBarRP=a==null?TEXT_NULL:a;$("#logout_MainBar").click(function(b){b.preventDefault();$.ajax({url:mainBarRP+"api/authentication/logout",async:false,type:"GET",success:function(){cookie_clearLoginUser();window.location.href=mainBarRP+PAGE_INDEX},error:function(c){notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})});$("#labelMe_MainBar").click(function(b){b.preventDefault()});a=cookie_get(COOKIE_USERNAME);$("#myOcean_MainBar").attr("href",mainBarRP+
PAGE_HOME);$("#addQuestion_MainBar").attr("href",mainBarRP+PAGE_ASKQUESTION);$("#trendradar_MainBar").attr("href",mainBarRP+PAGE_FINDFRIENDS);$("#settings_MainBar").attr("href",mainBarRP+PAGE_ACCOUNT);$("#randomText_MainBar").attr("href",mainBarRP+PAGE_ABOUT);$("#profile_MainBar").attr("href",mainBarRP+a);$("#following_MainBar").attr("href",mainBarRP+"follow/"+cookie_get(COOKIE_USERNAME)+ANCHOR_FOLLOWEDS);$("#followers_MainBar").attr("href",mainBarRP+"follow/"+cookie_get(COOKIE_USERNAME)+ANCHOR_FOLLOWERS);
$("#msgs_MainBar").attr("title","comingsoon");$("#msgs_MainBar").click(function(b){b.preventDefault()});$("#msgs_MainBar_Count").removeClass();$("#msgs_MainBar_Count").addClass("redreal");$("#msgs_MainBar_Count").click(function(b){b.preventDefault()});$("#nondropMsgs_MainBar").attr("title","comingsoon");$("#nondropMsgs_MainBar").click(function(b){b.preventDefault()});$("#msgs_MainBar").hide();$("#msgs_MainBar_Count").hide();$("#nondropMsgs_MainBar").hide();$("#coffees_MainBar").attr("title","my coffees");
$("#coffees_MainBar").attr("href",mainBarRP+a+ANCHOR_MYCOFFEE);$("#coffees_MainBar_Count").removeClass();$("#coffees_MainBar_Count").addClass("redreal");$("#coffees_MainBar_Count").attr("href",mainBarRP+a+ANCHOR_MYCOFFEE);$("#nondropCoffee_MainBar").attr("title","my coffees");$("#nondropCoffee_MainBar").attr("href",mainBarRP+a+ANCHOR_MYCOFFEE);$("#drops_mainBar").attr("title","my drops");$("#drops_MainBar").attr("href",mainBarRP+a+ANCHOR_DROPS);$("#drops_MainBar_Count").removeClass();$("#drops_MainBar_Count").addClass("redreal");
$("#drops_MainBar_Count").attr("href",mainBarRP+a+ANCHOR_DROPS);$("#nondropDrops_MainBar").attr("title","my drops");$("#nondropDrops_MainBar").attr("href",mainBarRP+a+ANCHOR_DROPS);$("#friends_MainBar").attr("title","new follower requests");$("#friends_MainBar").attr("href",mainBarRP+PAGE_NEWFOLLOWERS);$("#friends_MainBar_Count").removeClass();$("#friends_MainBar_Count").addClass("redreal");$("#friends_MainBar_Count").attr("href",mainBarRP+PAGE_NEWFOLLOWERS);$("#nondropFriends_MainBar").attr("title",
"new follower requests");$("#nondropFriends_MainBar").attr("href",mainBarRP+PAGE_NEWFOLLOWERS);$("#coffees_MainBar_Count").hide();$("#drops_MainBar_Count").hide();$("#friends_MainBar_Count").hide();if(common_checkActivated()){mainBar_refreshInfo();mainBar_updateScore();mainBar_updateNotificationCounts();mainBar_startTimer()}else mainBar_refreshInfo()}function mainBar_stopTimer(){clearInterval(mainBarNotificationCountsUpdater)}
function mainBar_startTimer(){mainBarNotificationCountsUpdater=setInterval("mainBar_updateNotificationCounts()",UPDATE_MAINBAR_NOTIFICATIONCOUNTS)}function mainBar_updateScore(){var a=cookie_get(COOKIE_LOGINUSER_TREND);if(a==null||a=="0.0")$.ajax({url:mainBarRP+"api/trends/"+cookie_get(COOKIE_USERNAME),type:"GET",success:function(b){b=$.evalJSON(b);$.cookie(COOKIE_LOGINUSER_TREND,b.trend);mainBar_refreshInfo()}});return false}
function mainBar_updateNotificationCounts(){$("#msgs_MainBar_Count").hide();$.ajax({url:mainBarRP+"api/messages/public/numberOfNotRead/",type:"GET",success:function(a){a=$.evalJSON(a);if(a.notReadPublicMessages=="0"){$("#coffees_MainBar_Count").hide();$("#coffees_MainBar_Count").text("")}else{$("#coffees_MainBar_Count").show();$("#coffees_MainBar_Count").text(a.notReadPublicMessages)}}});$.ajax({url:mainBarRP+"api/users/follow/numberOfFollowRequests/",type:"GET",success:function(a){a=$.evalJSON(a);
if(a.numberOfFollowRequests=="0")$("#friends_MainBar_Count").hide();else{$("#friends_MainBar_Count").show();$("#friends_MainBar_Count").text(a.numberOfFollowRequests)}}});$.ajax({url:mainBarRP+"api/notification/count/",type:"GET",success:function(a){a=$.evalJSON(a);if(a.notificationCount=="0")$("#drops_MainBar_Count").hide();else{$("#drops_MainBar_Count").show();$("#drops_MainBar_Count").text(a.notificationCount)}}});return false}
function mainBar_initializeSearch(a){$("#searchField_MainBar").blur();if(a){$(window).unload(function(){$("#searchField_MainBar").val(TEXT_NULL);$.cookie("searchContent",null)});$("#searchButton_MainBar").click(function(b){b.preventDefault();search_searchInQuestionsOrPeople()});$("#searchField_MainBar").keydown(function(b){if(b.keyCode==KEY_ENTER){b.preventDefault();search_searchInQuestionsOrPeople()}});a=cookie_get(COOKIE_SEARCH_CONTENT);if(a!=null){$("#searchField_MainBar").val(a);$("#searchButton_MainBar").click()}}else{$("#searchButton_MainBar").click(function(b){b.preventDefault();
b=$("#searchField_MainBar").val();if(b!=null&&b!=TEXT_NULL){cookie_wrap(COOKIE_SEARCH_CONTENT,b,false);window.location.href=mainBarRP+PAGE_SEARCH}});$("#searchField_MainBar").keydown(function(b){if(b.keyCode==KEY_ENTER){var c=$("#searchField_MainBar").val();if(c!=null&&c!=TEXT_NULL&&c!="Search"){$.cookie("searchContent",c);b.preventDefault();window.location.href=mainBarRP+PAGE_SEARCH}}})}}
function mainBar_signPageName(a){if(a==MAINBAR_LINK_MYOCEAN){$("#myOcean_MainBar").removeClass("nondrop");$("#myOcean_MainBar").addClass("nondrop_1")}else if(a==MAINBAR_LINK_PROFILE)if(profileUsername==profileLoginUserName){$("#profile_MainBar").removeClass("nondrop");$("#profile_MainBar").addClass("nondrop_1")}}function mainBar_unsignPageName(){};
