redirection_toClearURL()||cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL&&redirection_execute(PAGE_ACCOUNT,PAGE_INDEX,ERR_MSG_PLEASE_SIGNIN);
$(document).ready(function(){if(!(cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL||redirection_isURLContainsSSLOrWWW())){theme_processDesign();document.title="TrendOcean / "+cookie_get(COOKIE_USERNAME)+"'s account";mainBar_signPageName(MAINBAR_LINK_SETTING);$(window).unload(function(){$.ajax({async:false,url:"api/users/"+cookie_get(COOKIE_USERNAME),type:"GET",success:function(a){cookie_wrap(COOKIE_AVATAR_SMALL_URL,a.smallAvatarURL);cookie_wrap(COOKIE_AVATAR_LARGE_URL,a.largeAvatarURL);$("#avatarID").attr("src",
a.smallAvatarURL)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});mainBar_unsignPageName(MAINBAR_LINK_SETTING)});$("#icoWaiting").hide();mainBar_initialize();mainBar_initializeSearch(false);notifyBar_initialize();mainLinks_initialize(PAGE_ACCOUNT);var e=cookie_get(COOKIE_USERNAME),j=cookie_get(COOKIE_EMAIL),f=cookie_get(COOKIE_COUNTRY_CODE),d=cookie_get(COOKIE_ABOUT),k=cookie_get(COOKIE_GENDER),l=cookie_get(COOKIE_LANGUAGE),m=cookie_get(COOKIE_EDUCATION),
g=cookie_get(COOKIE_CITY_ID),n=cookie_get(COOKIE_MARGINAL),h=cookie_get(COOKIE_FULLNAME),o=cookie_get(COOKIE_BIRTH),p=cookie_get(COOKIE_AVATAR_SMALL_URL),q=cookie_get(COOKIE_ANSWER_VISB),r=cookie_get(COOKIE_EMAIL_VISB),s=cookie_get(COOKIE_PROFILE_VISB);if($.browser.msie){if(d==null)d="";$("#gender_register").append(common_newOption(TEXT_SELECT,TEXT_SELECT));$("#gender_register").append(common_newOption(TEXT_MALE,TEXT_MALE_BIG));$("#gender_register").append(common_newOption(TEXT_FEMALE,TEXT_FEMALE_BIG));
$("#education_account").append(common_newOption("Bachelor","BACHELOR"));$("#education_account").append(common_newOption("High School or Lower","HIGH_SCHOOL_OR_LOWER"));$("#education_account").append(common_newOption("Master or Higher","MASTER_OR_HIGHER"));$("#answerprivacy_account").append(common_newOption("Only Me","ONLY_ME"));$("#answerprivacy_account").append(common_newOption("Only Friends","ONLY_FRIENDS"));$("#answerprivacy_account").append(common_newOption("Everyone","EVERYONE"));$("#language_account").append(common_newOption("English",
"EN"));$("#gender_account").append(common_newOption("Male","MALE"));$("#gender_account").append(common_newOption("Female","FEMALE"));for(i=1;i<32;i++)$("#day_account").append(common_newOption(i+TEXT_NULL,i+TEXT_NULL));$.each(["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],function(a,b){$("#month_account").append(common_newOption(b,a))});$.ajax({url:"api/country/",type:"GET",success:function(a){$.each(a.country,function(b,c){$("#country_account").append(common_newOption(c.name,
c.code))});$("select#country_account").val(f);$("select#country_account").change()},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});$("#country_account").change(function(){$("#city_account").find("option").remove().end();$.ajax({url:"api/country/"+$("#country_account").val()+"/cities/",type:"GET",success:function(a){$.isArray(a.city_or_state)?$.each(a.city_or_state,function(b,c){$("#city_account").append(common_newOption(c.cityName,c.id))}):$("#city_account").append(common_newOption(a.city_or_state.cityName,
a.city_or_state.id));$("select#city_account").val(g)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}})})}else{$("#gender_register").append(new Option(TEXT_SELECT,TEXT_SELECT));$("#gender_register").append(new Option(TEXT_MALE,TEXT_MALE_BIG));$("#gender_register").append(new Option(TEXT_FEMALE,TEXT_FEMALE_BIG));$("#education_account").append(new Option("Bachelor","BACHELOR"));$("#education_account").append(new Option("High School or Lower","HIGH_SCHOOL_OR_LOWER"));
$("#education_account").append(new Option("Master or Higher","MASTER_OR_HIGHER"));$("#answerprivacy_account").append(new Option("Only Me","ONLY_ME"));$("#answerprivacy_account").append(new Option("Only Friends","ONLY_FRIENDS"));$("#answerprivacy_account").append(new Option("Everyone","EVERYONE"));$("#language_account").append(new Option("English","EN"));$("#gender_account").append(new Option("Male","MALE"));$("#gender_account").append(new Option("Female","FEMALE"));for(i=1;i<32;i++)$("#day_account").append(new Option(i+
TEXT_NULL,i+TEXT_NULL));$.each(["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"],function(a,b){$("#month_account").append(new Option(b,a))});$.ajax({url:"api/country/",type:"GET",success:function(a){$.each(a.country,function(b,c){$("#country_account").append(new Option(c.name,c.code))});$("select#country_account").val(f);$("select#country_account").change()},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});$("#country_account").change(function(){$("#city_account").find("option").remove().end();
$.ajax({url:"api/country/"+$("#country_account").val()+"/cities/",type:"GET",success:function(a){$.isArray(a.city_or_state)?$.each(a.city_or_state,function(b,c){$("#city_account").append(new Option(c.cityName,c.id))}):$("#city_account").append(new Option(a.city_or_state.cityName,a.city_or_state.id));$("select#city_account").val(g)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}})})}$("#avatarID").attr("src",p);$("#acountUserName").val(e);$("#fullname_account").val(h);
$("select#education_account").val(m);$("#email_account").val(j);$("#about_account").val(d);$("#fullName_account").val(h);$("#answerprivacy_account").val(q);r==TEXT_FALSE&&$("#emailprivacy_account").attr("checked","checked");s==TEXT_FALSE&&$("#privacy_account").attr("checked","checked");n==TEXT_TRUE?$("#marginal").attr("checked","checked"):$("#trend").attr("checked","checked");$("#btnSaveAvatar").click(function(a){common_checkPOST()||a.preventDefault()});$("#btnDeleteAvatar").click(function(a){a.preventDefault();
if(common_checkPOST()){a.preventDefault();$.ajax({url:"api/users/avatar",type:"DELETE",success:function(){window.location.href=jQuery.url.attr("source")},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}});return false}});$("#saveAccount").click(function(a){a.preventDefault();if($("#fullname_account").val().length==0)notifyBar_display("fullname is empty",ICON_URL_NOTIFY_WRONG);else if(common_checkPOST()){$("#icoWaiting").show();a={};a.username=e;a.fullName=
$("#fullname_account").val();a.gender=k;a.birthday=o;a.about=$("#about_account").val();a.language=l;a.education=$("#education_account").val();a.countryCode=$("#countr_account").val();a.cityID=$("#city_account").val();a.answerVisibility=$("#answerprivacy_account").val();a.emailPublic=!$("#emailprivacy_account").is(":checked");a.profilePublic=!$("#privacy_account").is(":checked");a.marginal=$("#marginal").is(":checked");a.email=$("#email_account").val();a=$.toJSON(a);$.ajax({url:"api/users/profile",
type:"PUT",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(b){$("#icoWaiting").hide();cookie_saveLoginUser(b,false);mainBar_refreshInfo();notifyBar_display(INFO_MSG_ACCOUNT_CHANGED,ICON_URL_NOTIFY_TRUE)},error:function(b){$("#icoWaiting").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}return false})}});
