cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL&&redirection_execute(PAGE_DESIGN,PAGE_INDEX,ERR_MSG_PLEASE_SIGNIN);
$(document).ready(function(){$("#txtLivePlayerSource").val(cookie_get(COOKIE_CAPABILITY_OF_LIVEPLAYERSOURCE));$("#txtLivePlayerSlogan").val(cookie_get(COOKIE_CAPABILITY_OF_LIVEPLAYERSLOGAN));cookie_get(COOKIE_CAPABILITY_OF_ASKED_TAB_VISB)==TEXT_TRUE&&$("#vsbAsked").attr("checked","checked");cookie_get(COOKIE_CAPABILITY_OF_ANSWERED_TAB_VISB)==TEXT_TRUE&&$("#vsbAnswered").attr("checked","checked");cookie_get(COOKIE_CAPABILITY_OF_LOVED_TAB_VISB)==TEXT_TRUE&&$("#vsbLoved").attr("checked","checked");cookie_get(COOKIE_CAPABILITY_OF_DROPS_TAB_VISB)==
TEXT_TRUE&&$("#vsbDrops").attr("checked","checked");cookie_get(COOKIE_CAPABILITY_OF_COFFEES_TAB_VISB)==TEXT_TRUE&&$("#vsbCoffee").attr("checked","checked");cookie_get(COOKIE_CAPABILITY_OF_PODCAST_TAB_VISB)==TEXT_TRUE&&$("#vsbPodcast").attr("checked","checked");$("#txtPodcast0_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST0_TITLE));$("#txtPodcast0_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST0_URL));$("#txtPodcast1_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST1_TITLE));$("#txtPodcast1_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST1_URL));
$("#txtPodcast2_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST2_TITLE));$("#txtPodcast2_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST2_URL));$("#txtPodcast3_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST3_TITLE));$("#txtPodcast3_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST3_URL));$("#txtPodcast4_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST4_TITLE));$("#txtPodcast4_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST4_URL));$("#txtPodcast5_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST5_TITLE));
$("#txtPodcast5_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST5_URL));$("#txtPodcast6_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST6_TITLE));$("#txtPodcast6_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST6_URL));$("#txtPodcast7_Title").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST7_TITLE));$("#txtPodcast7_URL").val(cookie_get(COOKIE_CAPABILITY_OF_PODCAST7_URL));$("#btnLivePlayerSource").click(function(a){a.preventDefault();if(common_checkPOST()){a={};a.source=$("#txtLivePlayerSource").val();
a.slogan=$("#txtLivePlayerSlogan").val();a=$.toJSON(a);$.ajax({url:"api/users/capabilityofliveplayer",type:"PUT",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(b){cookie_saveLoginUser(b,false)},error:function(){}})}return false});$("#btnPodcast").click(function(a){a.preventDefault();if(common_checkPOST()){a={};a.podcast0Title=$("#txtPodcast0_Title").val();a.podcast0URL=$("#txtPodcast0_URL").val();a.podcast1Title=$("#txtPodcast1_Title").val();a.podcast1URL=$("#txtPodcast1_URL").val();
a.podcast2Title=$("#txtPodcast2_Title").val();a.podcast2URL=$("#txtPodcast2_URL").val();a.podcast3Title=$("#txtPodcast3_Title").val();a.podcast3URL=$("#txtPodcast3_URL").val();a.podcast4Title=$("#txtPodcast4_Title").val();a.podcast4URL=$("#txtPodcast4_URL").val();a.podcast5Title=$("#txtPodcast5_Title").val();a.podcast5URL=$("#txtPodcast5_URL").val();a.podcast6Title=$("#txtPodcast6_Title").val();a.podcast6URL=$("#txtPodcast6_URL").val();a.podcast7Title=$("#txtPodcast7_Title").val();a.podcast7URL=$("#txtPodcast7_URL").val();
a=$.toJSON(a);$.ajax({url:"api/users/capabilityofpodcast",type:"PUT",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(b){cookie_saveLoginUser(b,false)},error:function(){}})}return false});$("#btnTabVisibility").click(function(a){a.preventDefault();if(common_checkPOST()){a={};a.askedTabVisb=$("#vsbAsked").is(":checked");a.answeredTabVisb=$("#vsbAnswered").is(":checked");a.lovedTabVisb=$("#vsbLoved").is(":checked");a.coffeeTabVisb=$("#vsbCoffee").is(":checked");
a.dropsTabVisb=$("#vsbDrops").is(":checked");a.podcastTabVisb=$("#vsbPodcast").is(":checked");a=$.toJSON(a);$.ajax({url:"api/users/capabilityoftabvisb",type:"PUT",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(b){cookie_saveLoginUser(b,false)},error:function(){}})}return false})});
