redirection_toClearURL()||cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL&&redirection_execute(PAGE_HOME,PAGE_INDEX,ERR_MSG_PLEASE_SIGNIN);theme_addCSSLink("home.css");theme_addCSSLink("default.css");theme_addCSSLink("dock.css");var searchPageIndex=1,homeQuestionQueryMode=QUESTIONS_IN_LATEST,homeQuestionUpdateRequired=false;
function home_updateQuestiotblComments(){homeQuestionUpdateRequired=false;if(homeQuestionQueryMode==QUESTIONS_IN_FOLLOW)$("#btnFriendsLatest").click();else if(homeQuestionQueryMode==QUESTIONS_IN_LATEST)$("#btnLatest").click();else if(homeQuestionQueryMode==QUESTIONS_IN_TODAY)$("#btnTodaySpecials").click();else homeQuestionQueryMode==QUESTIONS_IN_PROMOTED?$("#btnPromoted").click():$("#btnMostPopular").click()}
function home_automaticUpdate(){if($(window).scrollTop()==0&&selected_question==null)home_updateQuestiotblComments();else homeQuestionUpdateRequired=true}function home_removeQuickLinksClass(){$("#btnFriendsLatest").removeClass();$("#btnMostPopular").removeClass();$("#btnLatest").removeClass();$("#btnTodaySpecials").removeClass();$("#btnPromoted").removeClass()}
function home_setQuestionQueryMode(a){homeQuestionQueryMode=a;home_removeQuickLinksClass();switch(homeQuestionQueryMode){case QUESTIONS_IN_PROMOTED:$("#btnFriendsLatest").addClass("quick_link");$("#btnMostPopular").addClass("quick_link");$("#btnLatest").addClass("quick_link");$("#btnTodaySpecials").addClass("quick_link");$("#btnPromoted").addClass("quick_link_selected");break;case QUESTIONS_IN_LATEST:$("#btnFriendsLatest").addClass("quick_link");$("#btnMostPopular").addClass("quick_link");$("#btnLatest").addClass("quick_link_selected");
$("#btnTodaySpecials").addClass("quick_link");$("#btnPromoted").addClass("quick_link");break;case QUESTIONS_IN_YEAR:$("#btnFriendsLatest").addClass("quick_link");$("#btnMostPopular").addClass("quick_link_selected");$("#btnLatest").addClass("quick_link");$("#btnTodaySpecials").addClass("quick_link");$("#btnPromoted").addClass("quick_link");break;case QUESTIONS_IN_TODAY:$("#btnFriendsLatest").addClass("quick_link");$("#btnMostPopular").addClass("quick_link");$("#btnLatest").addClass("quick_link");$("#btnTodaySpecials").addClass("quick_link_selected");
$("#btnPromoted").addClass("quick_link");break;default:$("#btnFriendsLatest").addClass("quick_link_selected");$("#btnMostPopular").addClass("quick_link");$("#btnLatest").addClass("quick_link");$("#btnTodaySpecials").addClass("quick_link");$("#btnPromoted").addClass("quick_link")}}
function home_getPromotedQuestions(){home_setQuestionQueryMode(QUESTIONS_IN_PROMOTED);$.ajax({url:"api/questions/promoted?size=50",type:"GET",success:function(a){tblQuestions_renderQuestions(a);return false},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}})}
function home_displayMorePromotedQuestions(){$("#tableLoadingIcon").show();var a=display_questions.length;a>0&&$.ajax({url:"api/questions/promoted?startQuestion="+display_questions[a-1].id+"&size=20",type:"GET",success:function(b){if(b!=null){b.question=display_questions.concat(b.question);tblQuestions_renderQuestions(b)}$("#tableLoadingIcon").hide();return false},error:function(b){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}
function home_getFollowedQuestions(){home_setQuestionQueryMode(QUESTIONS_IN_FOLLOW);$.ajax({url:"api/questions/followed?size=20",type:"GET",success:function(a){tblQuestions_renderQuestions(a);return false},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}})}
function home_displayMoreFollowedQuestions(){$("#tableLoadingIcon").show();var a=display_questions.length;a>0&&$.ajax({url:"api/questions/followed?startQuestion="+display_questions[a-1].id+"&size=20",type:"GET",success:function(b){if(b!=null){b.question=display_questions.concat(b.question);tblQuestions_renderQuestions(b)}$("#tableLoadingIcon").hide();return false},error:function(b){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}
function home_getLatestQuestions(){home_setQuestionQueryMode(QUESTIONS_IN_LATEST);$.ajax({url:"api/questions?size=20",type:"GET",success:function(a){tblQuestions_renderQuestions(a);return false},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}})}
function home_displayMoreLatestQuestions(){$("#tableLoadingIcon").show();var a=display_questions.length;a>0&&$.ajax({url:"api/questions?startIndex="+display_questions[a-1].id+"&size=20",type:"GET",success:function(b){if(b!=null){b.question=display_questions.concat(b.question);tblQuestions_renderQuestions(b)}$("#tableLoadingIcon").hide();return false},error:function(b){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}
function home_getPopularQuestions(a){home_setQuestionQueryMode(a);$.ajax({url:"api/questions/popular?type="+a,type:"GET",success:function(b){tblQuestions_renderQuestions(b);return false},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}
function home_displayMorePopularQuestions(){$("#tableLoadingIcon").show();var a=display_questions.length;a>0&&$.ajax({url:"api/questions/popular?type="+homeQuestionQueryMode+"&startIndex="+a,type:"GET",success:function(b){if(b!=null){b.question=display_questions.concat(b.question);tblQuestions_renderQuestions(b)}$("#tableLoadingIcon").hide();return false},error:function(b){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}
function home_displayMoreSearchQuestions(){$("#tableLoadingIcon").show();$.ajax({url:"api/questions/search?searchTerm="+QUESTIONS_IN_TRENDS_TYPE+"&pageIndex="+searchPageIndex,type:"GET",success:function(a){if(a!=null){searchPageIndex++;a.question=display_questions.concat(a.question);tblQuestions_renderQuestions(a)}$("#tableLoadingIcon").hide()},error:function(a){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});return false}
function home_searchInQuestions(a){searchPageIndex=1;home_setQuestionQueryMode(QUESTIONS_IN_TRENDS);QUESTIONS_IN_TRENDS_TYPE=a;$.ajax({url:"api/questions/search?searchTerm="+a,type:"GET",success:function(b){tblQuestions_renderQuestions(b)},error:function(){tblQuestions_renderQuestions()}});return false}
$(document).ready(function(){if(!(cookie_get(COOKIE_SIGNIN)!=COOKIE_SIGNIN_VAL||redirection_isURLContainsSSLOrWWW())){theme_processDesign();document.title="TrendOcean / "+cookie_get(COOKIE_USERNAME)+"'s home";mainBar_signPageName(MAINBAR_LINK_MYOCEAN);$(window).unload(function(){mainBar_unsignPageName(MAINBAR_LINK_MYOCEAN)});mainLinks_initialize(PAGE_HOME);mainBar_initialize();mainBar_initializeSearch();notifyBar_initialize();redirection_executeOrderAfterNewPageLoad();shareDlg_initialize();askquick_initialize();
profileTab_initialize();profileTab_setContent();tblQuestions_initialize();coffeeDlg_initialize();home_getLatestQuestions();homeTrb_initialize();$("#askquick_textArea").counter({dispID:"asknow_counter",goal:"140",dispIDColor:"#ccc"});$(".answers_cho").click(function(){var a={};a.questionID=selected_question.id;a.choiceIndex="2";a=$.toJSON(a);$.ajax({url:"api/answers",type:"POST",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(){$("#rounder").show();$("#que_linked_part1").show();
$("#que_linked_part2").show()},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}});return false});common_preventScreenFlash();common_registerMoreActionListener(function(){if($("#tableLoadingIcon").is(":visible")==false)if(homeQuestionQueryMode==QUESTIONS_IN_FOLLOW)home_displayMoreFollowedQuestions();else if(homeQuestionQueryMode==QUESTIONS_IN_LATEST)home_displayMoreLatestQuestions();else if(homeQuestionQueryMode!=QUESTIONS_IN_PROMOTED)homeQuestionQueryMode==
QUESTIONS_IN_TRENDS?home_displayMoreSearchQuestions():home_displayMorePopularQuestions(homeQuestionQueryMode)});setInterval("home_automaticUpdate()",9E4);$(window).scroll(function(){$(window).scrollTop()==0&&selected_question==null&&homeQuestionUpdateRequired==true&&home_updateQuestiotblComments()});$("#btnPromoted").hide()}});
