if(!redirection_toClearURL("../")){var anchor=jQuery.url.attr("anchor");if(anchor==null){var address=window.location.href+ANCHOR_MYQUESTIONS;window.location.href=address.replace("##","#")}}theme_addCSSLink("profilebeta.css");theme_addCSSLink("default.css");theme_addCSSLink("dock.css");
var profileLoginUserName,profileUsername,profileFullName,profileCity,profileEducation,profileMail,profileAbout,profileMarginal,profileTrend,profileSmallAvatarURL,profileLargeAvatarURL,profileBgImageURL,profileBgImageTiled,profileScore=0,profileLovedCount=0,profileQuestionCount=0,profileAnsweredCount=0,profileQuestionsFavedCount=0,profileVisitedOtherCount=0,profileVerified=false,profileFollowedCount=0,profileFollowerCount=0,profileFollowing=TEXT_FALSE,profileFollowed=TEXT_FALSE,profileVisibility=TEXT_TRUE,
profileHasLivePlayer=TEXT_FALSE,profileLivePlayerSource="",profileLivePlayerSlogan="",profileAskedTabVisb=TEXT_FALSE,profileAnsweredTabVisb=TEXT_FALSE,profileLovedTabVisb=TEXT_FALSE,profilePodcastTabVisb=TEXT_FALSE,profileCurrentAnchor=null,coffeeUpdateTimer=null,profileHasPodcast=TEXT_FALSE,podcast0Title="",podcast1Title="",podcast2Title="",podcast3Title="",podcast4Title="",podcast5Title="",podcast6Title="",podcast7Title="",podcast0URL="",podcast1URL="",podcast2URL="",podcast3URL="",podcast4URL=
"",podcast5URL="",podcast6URL="",podcast7URL="",profileActivePodcast="";function profile_isVisibleToLoginUser(){if(profileUsername==profileLoginUserName)return true;if(profileVisibility==TEXT_TRUE)return true;else if(profileFollowing==TEXT_TRUE)return true;return false}
function fireAnchorTabChanged(a){$("#podc_headline_main").hide();if(profile_isVisibleToLoginUser()){profileCurrentAnchor=a;clearInterval(coffeeUpdateTimer);if(a==ANCHOR_MYQUESTIONS){document.title="TrendOcean / "+profileUsername+"'s questions";profile_getQuestions(API_PROFILE_MYQUESTIONS)}else if(a==ANCHOR_ANSWERED){document.title="TrendOcean / "+profileUsername+"'s answered";profile_getQuestions(API_PROFILE_ANSWEREDS)}else if(a==ANCHOR_LOVED){document.title="TrendOcean / "+profileUsername+"'s loved";
profile_getQuestions(API_PROFILE_FAVS)}else if(a==ANCHOR_MYCOFFEE){document.title="TrendOcean / "+profileUsername+"'s coffee";profile_getMyCoffeees();coffeeUpdateTimer=setInterval("profile_getMyCoffeees()",UPDATE_DELAY_MYCOFFEE)}else if(a==ANCHOR_PODCAST){document.title="TrendOcean / "+profileUsername+"'s podcasts";profile_getPodcasts();$("#podc_headline_main").show()}else if(a==ANCHOR_DROPS)if(profileUsername==profileLoginUserName){document.title="TrendOcean / "+profileUsername+"'s drops";profile_getDrops();
coffeeUpdateTimer=setInterval("profile_getDrops()",UPDATE_DELAY_MYCOFFEE)}else window.location.href=PAGE_OPPS}}
function profile_setProfileInfo(){if(profile_isVisibleToLoginUser()){$("#networks_profile").show();$("#education_profile").show();$("#email_profile").show();$("#about_profile").show();$("#trend_profile").show();$("#youme_trendocean").show();$("#profile_actions").show();$("#private_profile").hide();$("#seperator_networks").show();$("#seperator_email").show();$("#askQuickSection").hide();$("#navi_act").show();$("#followTab").show();$("#btnMsg").hide();profileUsername==profileLoginUserName?$("#btnCoffee").hide():
$("#btnCoffee").show();$("#fullname_profile").html(profileFullName);$("#username_profile").html(profileUsername);$("#photoID_profile").attr("src",profileSmallAvatarURL);$("#networks_profile").html(profileCity);$("#education_profile").html(profileEducation);$("#email_profile").html(profileMail);$("#about_profile").html(profileAbout);if(profileUsername==profileLoginUserName){$("#budgetquestionLabel_profile").text("you asked");$("#info_visit").text(profileVisitedOtherCount+" visit");$("#info_visit").show()}else{$("#budgetquestionLabel_profile").text(profileUsername+
" asked");$("#info_visit").hide()}$("#budgetquestion_profile").text(profileQuestionCount+" questions");$("#budgetanswered_profile").html(profileAnsweredCount+" answered");$("#budgetlove_profile").html(profileLovedCount+" loved");$("#budgetLoveLabel_profile").text("and they loved "+profileQuestionsFavedCount+" times.");coffeeDlg_setContent(profileUsername,cookie_get(COOKIE_USERNAME),profileSmallAvatarURL);followTab_setContent(profileUsername);followTab_followBtn_setContent();followTab_fillFollowers(12);
followTab_fillFolloweds(12);$("#following_btnAll").text(TEXT_FOLLOWEDS+profileFollowedCount);$("#follower_btnAll").text(TEXT_FOLLOWERS+profileFollowerCount);if(profileUsername!=profileLoginUserName){$("#tab_drops").hide();$("#tab_mycoffee").hide()}profileAskedTabVisb==TEXT_FALSE&&$("#tab_myquestions").hide();profileAnsweredTabVisb==TEXT_FALSE&&$("#tab_answered").hide();profileLovedTabVisb==TEXT_FALSE&&$("#tab_loved").hide();profilePodcastTabVisb==TEXT_FALSE&&$("#tab_podcast").hide();podcast0Title!=
TEXT_NULL&&$("#podc_0").text(podcast0Title);podcast1Title!=TEXT_NULL&&$("#podc_1").text(podcast1Title);podcast2Title!=TEXT_NULL&&$("#podc_2").text(podcast2Title);podcast3Title!=TEXT_NULL&&$("#podc_3").text(podcast3Title);podcast4Title!=TEXT_NULL&&$("#podc_4").text(podcast4Title);podcast5Title!=TEXT_NULL&&$("#podc_5").text(podcast5Title);podcast6Title!=TEXT_NULL&&$("#podc_6").text(podcast6Title);podcast7Title!=TEXT_NULL&&$("#podc_7").text(podcast7Title)}else{$("#fullname_profile").html(profileFullName);
$("#username_profile").html(profileUsername);$("#photoID_profile").attr("src",profileSmallAvatarURL);$("#networks_profile").html(profileCity);$("#header_private").html(profileFullName+"'s profile is private");$("#about_profile").html(profileAbout);coffeeDlg_setContent(profileUsername,cookie_get(COOKIE_USERNAME),profileSmallAvatarURL);followTab_setContent(profileUsername);followTab_followBtn_setContent();$("#education_profile").hide();$("#email_profile").hide();$("#about_profile").show();$("#trend_profile").hide();
$("#private_profile").show();$("#youme_trendocean").hide();$("#profile_actions").hide();$("#private_profile").show();$("#seperator_networks").hide();$("#seperator_email").hide();$("#askQuickSection").hide();$("#navi_act").hide();$("#followTab").hide();$("#btnCoffee").show();$("#btnMsg").show();tblCoffees_renderCoffees(null);tblQuestions_renderQuestions(null)}profileVerified==TEXT_FALSE?$("#verified_profile").hide():$("#verified_profile").show();if(profileBgImageURL!=TEXT_NULL){$("body").css("background-position",
"0px 0px");$("body").css("background-image","url("+profileBgImageURL+")");profileBgImageTiled==TEXT_TRUE?$("body").css("background-repeat","repeat"):$("body").css("background-repeat","no-repeat")}if(profileHasLivePlayer==TEXT_TRUE){$("#livePlayerName").text("listen "+profileUsername);$("#livePlayerSlogan").text(profileLivePlayerSlogan);$("#stopRO").hide();$("#playRO").click(function(a){a.preventDefault();a='<embed type="application/x-mplayer2" src="{liveplayersource}" width="1" height="1" autostart="1" balance="0" pluginspage="http://www.microsoft.com/Windows/Downloads/Contents/MediaPlayer/">';
a=a.replace("{liveplayersource}",profileLivePlayerSource);$("#embedRO").html(a);$("#playRO").hide();$("#stopRO").show()});$("#stopRO").click(function(a){a.preventDefault();$("#embedRO").empty();$("#playRO").show();$("#stopRO").hide()})}else $("#radyoodtu_player").hide()}
function profile_updateProfile(){$.ajax({url:"api/users/"+profileUsername,type:"GET",success:function(a){profileFullName=a.fullName;profileCity=a.city;profileEducation=a.education;profileMail=a.email;profileAbout=a.about;profileMarginal=a.marginal;profileQuestionCount=a.questionsAsked;profileQuestionsFavedCount=a.questionsFavedCount;profileAnsweredCount=a.questionsAnswered;profileLovedCount=a.favoriteCount;profileFollowedCount=a.followedCount;profileFollowerCount=a.followerCount;profileFollowing=
a.following;profileFollowed=a.followed;profileSmallAvatarURL=a.smallAvatarURL;profileLargeAvatarURL=a.largeAvatarURL;profileVisibility=a.profilePublic;profileVisitedOtherCount=a.profileViewCount;profileTrend=a.trend;profileBgImageURL=a.design.backgroundURL;profileBgImageTiled=a.design.backgroundTiled;profileVerified=a.verified;profileHasLivePlayer=a.capabilities.hasLivePlayer;profileLivePlayerSource=a.capabilities.livePlayerCapability.source;profileLivePlayerSlogan=a.capabilities.livePlayerCapability.slogan;
profileAskedTabVisb=a.capabilities.tabVisibiltyCapability.askedTabVisb;profileAnsweredTabVisb=a.capabilities.tabVisibiltyCapability.answeredTabVisb;profileLovedTabVisb=a.capabilities.tabVisibiltyCapability.lovedTabVisb;profilePodcastTabVisb=a.capabilities.tabVisibiltyCapability.podcastTabVisb;profileHasPodcast=a.capabilities.hasPodcastTab;podcast0URL=a.capabilities.podcastCapability.podcast0URL;podcast0Title=a.capabilities.podcastCapability.podcast0Title;podcast1URL=a.capabilities.podcastCapability.podcast1URL;
podcast1Title=a.capabilities.podcastCapability.podcast1Title;podcast2URL=a.capabilities.podcastCapability.podcast2URL;podcast2Title=a.capabilities.podcastCapability.podcast2Title;podcast3URL=a.capabilities.podcastCapability.podcast3URL;podcast3Title=a.capabilities.podcastCapability.podcast3Title;podcast4URL=a.capabilities.podcastCapability.podcast4URL;podcast4Title=a.capabilities.podcastCapability.podcast4Title;podcast5URL=a.capabilities.podcastCapability.podcast5URL;podcast5Title=a.capabilities.podcastCapability.podcast5Title;
podcast6URL=a.capabilities.podcastCapability.podcast6URL;podcast6Title=a.capabilities.podcastCapability.podcast6Title;podcast7URL=a.capabilities.podcastCapability.podcast7URL;podcast7Title=a.capabilities.podcastCapability.podcast7Title;profileActivePodcast=podcast0URL;profile_setProfileInfo();anchorTab_initialize();profileMatch_initialize();common_preventScreenFlash();profile_updateScore()},error:function(){window.location.href=PAGE_OPPS}});return false}
function profile_updateScore(){if(profileUsername!=profileLoginUserName){$.ajax({url:"api/trends/"+profileUsername,type:"GET",success:function(d){profileTrend=$.evalJSON(d).trend;d=TEXT_TRENDY;var e="";if(profileMarginal==TEXT_TRUE){d=TEXT_MARGINAL;e=100-parseInt(parseFloat(profileTrend)*100)}else{d=TEXT_TRENDY;e=parseInt(parseFloat(profileTrend)*100)}$("#trend_profile").text(e+"% "+d)}});return false}else{var a=cookie_get(COOKIE_LOGINUSER_TREND),b=TEXT_TRENDY,c=0;if(cookie_get(COOKIE_MARGINAL)==
TEXT_TRUE){b=TEXT_MARGINAL;c=100-parseInt(parseFloat(a)*100)}else c=parseInt(parseFloat(a)*100);$("#trend_profile").text(c+"% "+b)}}
function profile_reflectActionsOnQuestions(a,b){if(profileUsername==profileLoginUserName)if(a==QACTIONS_ANSWERED){profileAnsweredCount=cookie_get(COOKIE_QUESTION_ANSWERED);$("#budgetanswered_profile").html(profileAnsweredCount+" answered")}else if(a==QACTIONS_FAVED){profileLovedCount=cookie_get(COOKIE_QUESTION_FAVED);$("#budgetlove_profile").html(profileLovedCount+" loved")}else if(a==QACTIONS_UNFAVED){profileLovedCount=cookie_get(COOKIE_QUESTION_FAVED);$("#budgetlove_profile").html(profileLovedCount+
" loved");profileCurrentAnchor==ANCHOR_LOVED&&tblQuestions_removeQuestion(b.id)}}function profile_getQuestions(a){$.ajax({url:a+profileUsername,type:"GET",success:function(b){tblQuestions_renderQuestions(b);return false},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}});return false}
function profile_getMoreQuestions(a){var b=0;if(display_questions!=null)b=display_questions.length;if(b>0){b=display_questions[b-1].id;$("#tableLoadingIcon").show();$.ajax({url:a+profileUsername+"?startIndex="+b+"&size=20",type:"GET",success:function(c){if(c!=null){c.question=display_questions.concat(c.question);tblQuestions_renderQuestions(c)}$("#tableLoadingIcon").hide()},error:function(c){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false}
function profile_getMyCoffeees(){$.ajax({url:"api/messages/public/"+profileUsername,type:"GET",success:function(a){tblCoffees_renderCoffees(a);if(profileLoginUserName==profileUsername){$("#coffees_MainBar_Count").hide();$("#coffees_MainBar_Count").text("0")}return false},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});return false}
function profile_getMoreMyCoffeees(){var a=display_coffees.length;if(a>0){a=display_coffees[a-1].id;$("#tableLoadingIcon").show();$.ajax({url:API_PROFILE_COFFEES+profileUsername+"?startIndex="+a+"&size=20",type:"GET",success:function(b){if(b!=null){b.message=display_coffees.concat(b.message);tblCoffees_renderCoffees(b)}$("#tableLoadingIcon").hide()},error:function(b){$("#tableLoadingIcon").hide();notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}})}return false}
function profile_getDrops(){$.ajax({url:"api/notification/",type:"GET",success:function(a){tblNotifications_render(a);if(profileLoginUserName==profileUsername){$("#drops_MainBar_Count").hide();$("#drops_MainBar_Count").text("0")}return false},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});return false}function profile_getMoreDrops(){}
function profile_getPodcasts(){tblPodcasts_renderPodcasts(null);$("#tableLoadingIcon").show();jQuery.getFeed({url:"api/comments/proxy?podcastURL="+profileActivePodcast,success:function(a){tblPodcasts_renderPodcasts(a);$("#tableLoadingIcon").hide()}})}function profile_getMorePodcasts(){}
$(document).ready(function(){if(!redirection_isURLContainsSSLOrWWW()){profileUsername=common_getURLSegment(0);profileLoginUserName=cookie_get(COOKIE_USERNAME);mainLinks_initialize(PAGE_PROFILE);shareDlg_initialize();coffeeDlg_initialize($("#btnCoffee"),PAGE_PROFILE);followTab_fallowBtn_initialize($("#btnFollow"));$("#askquick_textArea").counter({dispID:"asknow_counter",goal:"140"});if(cookie_get(COOKIE_SIGNIN)==COOKIE_SIGNIN_VAL){$("#headerdock").hide();$(".right-person-navi").show();mainBar_signPageName(MAINBAR_LINK_PROFILE);
$(window).unload(function(){mainBar_unsignPageName(MAINBAR_LINK_PROFILE)});mainBar_initialize();mainBar_initializeSearch()}else{$("#docka").hide();$("#toolbar_rightpersoninfo").hide();$(".right-person-navi").hide();$("#logoToHome2").click(function(a){a.preventDefault();window.location.href=PAGE_INDEX});$("#following_btnAll").click(function(a){a.preventDefault()});$("#follower_btnAll").click(function(a){a.preventDefault()})}notifyBar_initialize();askquick_initialize();tblQuestions_initialize(PAGE_PROFILE);
tblCoffees_initialize();tblPodcasts_initialize();tblNotifications_initialize();profile_updateProfile();common_registerMoreActionListener(function(){if($("#tableLoadingIcon").is(":visible")==false)if(profileCurrentAnchor==ANCHOR_MYQUESTIONS)profile_getMoreQuestions(API_PROFILE_MYQUESTIONS);else if(profileCurrentAnchor==ANCHOR_ANSWERED)profile_getMoreQuestions(API_PROFILE_ANSWEREDS);else if(profileCurrentAnchor==ANCHOR_LOVED)profile_getMoreQuestions(API_PROFILE_FAVS);else if(profileCurrentAnchor==ANCHOR_MYCOFFEE)profile_getMoreMyCoffeees();
else if(profileCurrentAnchor==ANCHOR_PODCAST)profile_getMorePodcasts();else profileCurrentAnchor==ANCHOR_DROPS&&profile_getMoreDrops()});$("#podc_0").click(function(a){a.preventDefault();profileActivePodcast=podcast0URL;profile_getPodcasts()});$("#podc_1").click(function(a){a.preventDefault();profileActivePodcast=podcast1URL;profile_getPodcasts()});$("#podc_2").click(function(a){a.preventDefault();profileActivePodcast=podcast2URL;profile_getPodcasts()});$("#podc_3").click(function(a){a.preventDefault();
profileActivePodcast=podcast3URL;profile_getPodcasts()});$("#podc_4").click(function(a){a.preventDefault();profileActivePodcast=podcast4URL;profile_getPodcasts()});$("#podc_5").click(function(a){a.preventDefault();profileActivePodcast=podcast5URL;profile_getPodcasts()});$("#podc_6").click(function(a){a.preventDefault();profileActivePodcast=podcast6URL;profile_getPodcasts()});$("#podc_7").click(function(a){a.preventDefault();profileActivePodcast=podcast7URL;profile_getPodcasts()});$("#podc_headline_main").hide();
$("#dlgMsg_title").text("Message");$("#dlgMsg_info").text("Send Trend Ocean a message:");$("#message_labelText").text("message:");$("#message_textcounter").text("300");$("#dlgMsg_lblSucceed").text("your  message has been sent.");$("#dlgMsg_sendBtn").text("send");$("#dlgCoffee_Title").text("Coffee");$("#dlgCoffee_lblSucceed").text("your coffee was sent.");$("#dlgCoffee_sendBtn").text("send");$("#dlgShare_Title").text("Share");$("#dlgShare_Info").text("Share one question via:");$("#dlgMsg_info").text("Share this question with your friend:");
$("#dlgShareEmail_Label").text("e-mail:");$("#dlgShareEmail_succeedLabel").text("shared via e-mail");$("#dlgShareEmail_sendBtn").text("share");$("#locked_text").html('When oceaner hide her/his answers from settings, the answer is not visible to everyone and you see locked image. for more information: <a href="http://trendocean.com/privacy.html">answer visibility</a>');$("#qRelated_More").text("more");$("#questionRelatedUsersTitle").text("Answered");$("#settings_MainBar").text("Settings");$("#following_MainBar").text("Following");
$("#followers_MainBar").text("Followers");$("#logout_MainBar").text("Sign Out");$("#myOcean_MainBar").text("My Ocean");$("#profile_MainBar").text("Profile");$("#trendradar_MainBar").text("trendradar");$("#addQuestion_MainBar").text("add question");$("#toMark").text("\u00a9 2011 TrendOcean");$("#aboutLink").text("About Us");$("#blogLink").text("Blog");$("#teamLink").text("Team");$("#businessLink").text("Business");$("#helpLink").text("Help");$("#termsLink").text("Terms")}});
