var drawingScriptLoaded=false,drawingDataLoaded=false,drawingGeoDataLoaded=false,statQuestion=null,statDist=null,statGeoDist=null,statChoiceCount=0,statChartWidth=270,statChartHeight=200;function statistics_initialize(){google.load("visualization","1",{packages:["corechart","geomap"]});google.setOnLoadCallback(staticstics_initialized)}function staticstics_initialized(){drawingScriptLoaded=true;statistics_drawChart()}function statistics_cropChoice(a){return statQuestion.choices[a]}
function statistics_drawInTurkey(){if(!(statGeoDist==null||statQuestion==null)){var a=parseInt(statQuestion.totalAnswerCount),b=new google.visualization.DataTable,c=0;if($.isArray(statGeoDist)==false){b.addRows(1);b.addColumn("string","City");b.addColumn("number","Ratio");b.setValue(0,0,statGeoDist.city.cityName);for(i=0;i<statChoiceCount;i++)c+=parseInt(statGeoDist.distribution[i].value);c=parseFloat((c*100/a).toFixed(1));b.setValue(0,1,c)}if($.isArray(statGeoDist)){b.addRows(statGeoDist.length);
b.addColumn("string","City");b.addColumn("number","Ratio");for(j=0;j<statGeoDist.length;j++){c=0;b.setValue(j,0,statGeoDist[j].city.cityName);for(i=0;i<statChoiceCount;i++)c+=parseInt(statGeoDist[j].distribution[i].value);c=parseFloat((c*100/a).toFixed(1));b.setValue(j,1,c)}}$("#chartTurkey_div").removeClass();a={};a.region="TR";a.colors=[16746311,16758145,12607488];a.dataMode="markers";a.width="540";c=document.getElementById("chartTurkey_div");(new google.visualization.GeoMap(c)).draw(b,a)}}
function statistics_drawGeoMap(){var a=new google.visualization.DataTable;a.addRows(6);a.addColumn("string","Country");a.addColumn("number","Popularity");a.setValue(0,0,"Turkey");a.setValue(0,1,1E3);a.setValue(1,0,"United States");a.setValue(1,1,300);a.setValue(2,0,"Brazil");a.setValue(2,1,400);a.setValue(3,0,"Canada");a.setValue(3,1,500);a.setValue(4,0,"France");a.setValue(4,1,600);a.setValue(5,0,"RU");a.setValue(5,1,700);var b={};b.dataMode="regions";var c=document.getElementById("chartGeoMap_div");
(new google.visualization.GeoMap(c)).draw(a,b)}
function statistics_drawTotal(){var a=new google.visualization.DataTable;a.addColumn("string","Choices");a.addColumn("number","Total");a.addRows(statChoiceCount);for(i=0;i<statChoiceCount;i++){a.setValue(i,0,statistics_cropChoice(i));a.setValue(i,1,parseInt(statDist[0].distribution[i].value)+parseInt(statDist[1].distribution[i].value))}(new google.visualization.PieChart(document.getElementById("chartTotal_div"))).draw(a,{width:statChartWidth,height:statChartHeight,is3D:true,title:"Choice Distribution"})}
function statistics_drawFM(){var a=new google.visualization.DataTable;a.addColumn("string","Choices");a.addColumn("number","M");a.addColumn("number","F");a.addRows(statChoiceCount);for(i=0;i<statChoiceCount;i++){a.setValue(i,0,statistics_cropChoice(i));a.setValue(i,1,parseInt(statDist[0].distribution[i].value));a.setValue(i,2,parseInt(statDist[1].distribution[i].value))}(new google.visualization.BarChart(document.getElementById("chartFM_div"))).draw(a,{width:statChartWidth,height:statChartHeight,
is3D:true,title:"Female/Male Statistics"})}function statistics_drawF(){var a=new google.visualization.DataTable;a.addColumn("string","Choices");a.addColumn("number","F");a.addRows(statChoiceCount);for(i=0;i<statChoiceCount;i++){a.setValue(i,0,statistics_cropChoice(i));a.setValue(i,1,parseInt(statDist[1].distribution[i].value))}(new google.visualization.PieChart(document.getElementById("chartOnlyF_div"))).draw(a,{width:statChartWidth,height:statChartHeight,is3D:true,title:"Female Statistics"})}
function statistics_drawM(){var a=new google.visualization.DataTable;a.addColumn("string","Choices");a.addColumn("number","M");a.addRows(statChoiceCount);for(i=0;i<statChoiceCount;i++){a.setValue(i,0,statistics_cropChoice(i));a.setValue(i,1,parseInt(statDist[0].distribution[i].value))}(new google.visualization.PieChart(document.getElementById("chartOnlyM_div"))).draw(a,{width:statChartWidth,height:statChartHeight,is3D:true,title:"Male Statistics"})}function statistics_drawAge(){}
function statistics_drawEducation(){}function statistics_drawChart(){if(drawingDataLoaded&&drawingScriptLoaded){statistics_drawF();statistics_drawM()}drawingGeoDataLoaded&&drawingScriptLoaded&&statistics_drawInTurkey()}
function statistics_display(a){statQuestion=a;statChoiceCount=a.choices.length;$.ajax({url:"../api/statistics/bygender/"+a.id,type:"GET",success:function(b){statDist=b.distribution;drawingDataLoaded=true;statistics_drawChart()},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+":"+b.status,ICON_URL_NOTIFY_WRONG)}});$.ajax({url:"../api/statistics/bycity/TR/"+a.id,type:"GET",success:function(b){statGeoDist=b.distribution;drawingGeoDataLoaded=true;statistics_drawChart()},error:function(b){notifyBar_display(ERR_MSG_WEBSERVICE+
":"+b.status,ICON_URL_NOTIFY_WRONG)}});return false};
