var tblFollows_RelativePath="",tblFollows_LoginedUser=cookie_get(COOKIE_USERNAME),tblFollows_Page="",follow_directive={"@id":'"user"',"div.follow_part":{"post <- user":{"div.follow_id":"post.username","a.badge@href":function(a){return tblFollows_RelativePath+a.item.username},"img.avatarImg@src":"post.smallAvatarURL","div.namebadge":"post.username","div.realname":"post.fullName","div.about":function(a){return common_htmlStrip(a.item.about)},"a.badgesendmessage@style":function(a){return a.item.username==
tblFollows_LoginedUser?"display:none":""},"a.badgesendcoffee@style":function(a){return a.item.username==tblFollows_LoginedUser?"display:none":""},"a.badgeaddfollow@style":function(a){return a.item.isFollowedByCurrentUser=="true"||a.item.username==tblFollows_LoginedUser||tblFollows_Page==PAGE_NEWFOLLOWERS?"display:none":""},"a.badgeaddunfollow@style":function(a){return a.item.isFollowedByCurrentUser=="false"||a.item.username==tblFollows_LoginedUser||tblFollows_Page==PAGE_NEWFOLLOWERS?"display:none":
""}}}},follow_template,display_follows=null,selected_follow=null,tblFollows_LoginedUserFolloweds=null,tblFollows_data=null;
function tblFollows_initialize(a,d){$("#btnMore").hide();$("#footer_nav").hide();if(a!=null)tblFollows_RelativePath=a;if(d!=null)tblFollows_Page=d;$(".follow_def").hide();follow_template=$("#foll_part").compile(follow_directive);$("#foll_part").hide();$("#tableLoadingIcon").hide();$(".badgesendcoffee").live("click",function(b){b.preventDefault();b=$(this).parents(".follow_part").children(":first-child").children(":first-child").text();selected_follow=tblFollows_getFollow(b);if(selected_follow!=null){b=
$(this).position();coffeeDlg_setContent(selected_follow.username,cookie_get(COOKIE_USERNAME),selected_follow.smallAvatarURL);coffeeDlg_show(b)}});$(".badgeaddfollow").live("click",function(b){b.preventDefault();if(common_checkPOST()){b=$(this).parents(".follow_part").children(":first-child").children(":first-child").text();selected_follow=tblFollows_getFollow(b);selected_follow!=null&&$.ajax({url:tblFollows_RelativePath+"api/users/follow/"+selected_follow.username,async:false,type:"POST",success:function(){selected_follow.isFollowedByCurrentUser=
"true";tblFollows_renderFollows(tblFollows_data)},error:function(c){notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG,tblFollows_RelativePath)}})}return false});$(".badgeaddunfollow").live("click",function(b){b.preventDefault();if(common_checkPOST()){b=$(this).parents(".follow_part").children(":first-child").children(":first-child").text();selected_follow=tblFollows_getFollow(b);selected_follow!=null&&$.ajax({url:tblFollows_RelativePath+"api/users/follow/"+selected_follow.username,
async:false,type:"DELETE",success:function(){var c=jQuery.url.setUrl(document.location).attr("anchor");if(cookie_get(COOKIE_USERNAME)==common_getURLSegment(1)&&c=="following"){tblFollows_removeFollow(selected_follow.username);selected_follow=null}else{selected_follow.isFollowedByCurrentUser="false";tblFollows_renderFollows(tblFollows_data)}},error:function(c){notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG,tblFollows_RelativePath)}})}return false});if(tblFollows_Page==PAGE_NEWFOLLOWERS){$(".badgeaccept").live("click",
function(b){b.preventDefault();b=$(this).parents(".follow_part").children(":first-child").children(":first-child").text();selected_follow=tblFollows_getFollow(b);if(selected_follow!=null){$.ajax({url:tblFollows_RelativePath+"api/users/follow/confirm/"+selected_follow.username,type:"POST",success:function(){var c=parseInt($("#friends_MainBar_Count").text());c--;$("#friends_MainBar_Count").text(c);newFollowers_displayMainText(c);tblFollows_removeFollow(selected_follow.username)},error:function(c){notifyBar_display(ERR_MSG_WEBSERVICE+
":"+c.status,ICON_URL_NOTIFY_WRONG,tblFollows_RelativePath)}});return false}});$(".badgedecline").live("click",function(b){b.preventDefault();if(common_checkPOST()){b=$(this).parents(".follow_part").children(":first-child").children(":first-child").text();selected_follow=tblFollows_getFollow(b);selected_follow!=null&&$.ajax({url:tblFollows_RelativePath+"api/users/follow/reject/"+selected_follow.username,type:"POST",success:function(){var c=parseInt($("#friends_MainBar_Count").text());c--;$("#friends_MainBar_Count").text(c);
newFollowers_displayMainText(c);tblFollows_removeFollow(selected_follow.username)},error:function(c){notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG,tblFollows_RelativePath)}})}return false})}}function tblFollows_getFollow(a){for(i=0;i<display_follows.length;i++){var d=display_follows[i];if(d.username==a)return d}return null}
function tblFollows_removeFollow(a){for(i=0;i<display_follows.length;i++)if(display_follows[i].username==a)break;display_follows.splice(i,1);tblFollows_renderFollows(tblFollows_data)}
function tblFollows_renderFollows(a){var d=$(window).scrollTop();$("#static_que_section").html("<div id=que_section></div>");if(a==null){a={};display_follows=null}else display_follows=$.isArray(a.user)?a.user:Array(a.user);tblFollows_data=a;tblFollows_data.user=display_follows;$("#que_section").render(tblFollows_data,follow_template);$(window).scrollTop(d)};
