var youtube="<iframe title='YouTube video player' class='youtube-player' type='text/html' width='400' height='240' src='http://www.youtube.com/embed/$youtubecode$?wmode=transparent' frameborder='0'></iframe>",vimeo="<iframe src='http://player.vimeo.com/video/$vimeocode$' width='400' height='240' frameborder='0'></iframe>",htmlImgURL="<img src='{url}' width='400'  height='240'/>",mediaDiv="<div id='question_media'></div>",soundCloud='<object id="toPlayer" classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"><param name=movie" value="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F$soundcloudCode1$%2F$soundcloudCode2$&enable_api=true&object_id=toPlayer"></param><param name="allowscriptaccess" value="always"></param><embed allowscriptaccess="always" height="81" wmode="transparent" src="http://player.soundcloud.com/player.swf?url=http%3A%2F%2Fsoundcloud.com%2F$soundcloudCode3$%2F$soundcloudCode4$&enable_api=true&object_id=toPlayer" type="application/x-shockwave-flash" width="400" name="toPlayer"></embed></object>',
directive={"@id":'"question"',"div.question_part":{"post <- question":{"div.question_id":"post.id","a.avatarImgLink@href":"post.owner","img.avatarImg@src":"post.ownerSmallAvatarURL","a.owner":"post.owner","a.owner@href":"post.owner","a.commentCount":"#{post.numberOfComments} comments","a.commentCount@href":"question/#{post.id}","a.qTotalAnswerCount":" #{post.totalAnswerCount} answered","a.qTotalLovedCount":"#{post.likedCount} love","a.video-navi@href":"question/#{post.id}","div.post_body":function(b){return common_contentProcess(b.item.body)},
"span.qCreationDate":function(b){return common_getRemainingTime(new Date(b.item.creationDate*1))},"span.trendsetting@style":function(b){return b.item.isPromoted=="true"?"":"display:none"},"a.love@style":function(){return"display:none"},"a.loveselected@style":function(){return"display:none"},"a.flag@style":function(){return"display:none"},"a.flagselected@style":function(){return"display:none"},"a.share@style":function(){return"display:none"},".coffeecup_sendbutton@style":function(){return"display:none"},
"a.video-navi@style":function(b){return common_isContainsMedia(b.item.body)?"":"display:none"},"a.btnAnswer":function(b){return tblQuestions_defineQNodeBtnText(b.item)},"a.infostat-navi@style":function(){return"display:none"},"a.infostat-navi@href":"question/#{post.id}#stat","span.reask-info@style":function(b){return b.item.reaskUser==TEXT_NULL||b.item.isPromoted=="true"?"display:none":""},"span.reask-info":"<b>reasked</b> by #{post.reaskUser}","span.reask-info-do@style":function(){return"display:none"},
"span.reask-info-remove@style":function(){return"display:none"}}}},selected_qBody=null,selected_qTotalAnswerCount=null,selected_qLovedCount=null,selected_qFlag=null,selected_qFlagSelected=null,selected_qLoved=null,selected_qLovedSelected=null,selected_qStat=null,render_template,question_answer_process=null,tblQuestionsData=null,display_questions=null,selected_question_choiceCount=0,selected_question=null,hover_question=null,selected_choice=null,selected_button=null,selected_button_prevText=null,tblQuestions_page=
"";
function tblQuestions_initialize(b){tblQuestionRelatedUsers_initialize();$("#btnMore").hide();$("#footer_nav").hide();$("#questionRelatedUsers").hide();if(tblQuestions_page!=null)tblQuestions_page=b;$(".question_def").hide();render_template=$("#que_part").compile(directive);question_answer_process=$("#question_answer_process");question_answer_process.prepend(mediaDiv);for(i=0;i<10;i++)$("#answers_cho"+i).data(DATA_CHOICE_INDEX,i);$("#que_part").hide();question_answer_process.hide();$("#waitingIcon").hide();$("#ichoosethis_onequestion").hide();
$("#statistic_onequestion").hide();$("#tableLoadingIcon").hide();$("#ichooseact_onequestion").live("click",function(a){a.preventDefault();if(common_checkAnswerPOST()){var c=cookie_get(COOKIE_LOGINUSER_TREND);$("#waitingIcon").show();var d={};d.questionID=selected_question.id;d.choiceIndex=selected_choice.data(DATA_CHOICE_INDEX);a=$.toJSON(d);$.ajax({url:"api/answers",type:"POST",data:a,dataType:"json",contentType:"application/json; charset=utf-8",success:function(e){tblQuestions_answerSucceeded(c,
d.choiceIndex,e)},error:function(e){$("#waitingIcon").hide();$("#ichoosethis_onequestion").hide();e.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(e.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+e.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".quendy").live("mouseenter ",function(){var a=$(this).parents(".question_part"),c=a.children(":first-child").children(":first-child").text();hover_question=tblQuestions_getQuestion(c);if(hover_question!=null){if(hover_question.answer!=
INDEX_OF_NOT_ANSWERED||hover_question.owner==cookie_get(COOKIE_USERNAME))a.find(".infostat-navi").show();hover_question.owner!=cookie_get(COOKIE_USERNAME)&&a.find(".coffeecup_sendbutton").show();hover_question.owner!=cookie_get(COOKIE_USERNAME)&&a.find(".reask-info-do").show();hover_question.isQuestionFaved=="false"?a.find(".love").show():a.find(".loveselected").show();hover_question.isQuestionAbused=="false"?a.find(".flag").show():a.find(".flagselected").show();a.find(".share").show()}});$(".quendy").live("mouseleave",
function(){var a=$(this).parents(".question_part");a.find(".infostat-navi").hide();a.find(".coffeecup_sendbutton").hide();a.find(".share").hide();a.find(".love").hide();a.find(".loveselected").hide();a.find(".flag").hide();a.find(".flagselected").hide();a.find(".reask-info-do").hide()});$(".btnAnswer").live("click",function(a){a.preventDefault();a=$(this).parent();var c=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qTotalAnswerCount=$(this).parents(".question_part").find(".qTotalAnswerCount");
selected_qStat=$(this).parents(".question_part").find(".infostat-navi");selected_qBody=$(this).parents(".question_part").find(".post_body");if(selected_button!=null){var d=selected_button.parents(".question_part").children(":first-child").children(":first-child").text();d!=c&&selected_button.text(tblQuestions_defineQNodeBtnText(tblQuestions_getQuestion(d)))}selected_question=tblQuestions_getQuestion(c);selected_button=$(this);if($(this)!=null)if($(this).text()==QNODE_BTN_CLOSE){question_answer_process.hide();
$(this).html(tblQuestions_defineQNodeBtnText(selected_question));selected_question=null;return false}else $(this).html(tblQuestions_defineQNodeBtnText(selected_question));if(selected_question!=null){$(this).html(QNODE_BTN_CLOSE);question_answer_process.appendTo(a);tblQuestions_prepareQuestionChoices(selected_question);$("#question_media").html(common_contentProcessing(selected_question.body,CONTENT_PROCESS_FOR_QUESTION_TABLE));$("#rounder").hide();$("#que_linked_part1").hide();$("#que_linked_part2").hide();
$("#ichoosethis_onequestion").hide();$("#statistic_onequestion").hide();if(selected_question.answer==INDEX_OF_NOT_ANSWERED){tblQuestions_clearChoiceSelection();gTable_bindEventToNonAnsweredQuestion()}else{tblQuestions_prepareChoiceDistribution(selected_question);tblQuestions_clearChoiceSelection();gTable_unbindChoiceEvents();gTable_bindEventToAnsweredQuestion();tblQuestions_signSelectedChoice(parseInt(selected_question.answer))}question_answer_process.show()}return false});$(".qTotalAnswerCount").live("click",
function(a){a.preventDefault();var c=$(this).offset();a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/answers/all/"+a,type:"GET",success:function(d){if(d!=null){$("#questionRelatedUsers").css("position","absolute");$("#questionRelatedUsers").css("top",c.top);$("#questionRelatedUsers").css("left",c.left);$("#questionRelatedUsersTitle").text("Answered");$("#questionRelatedUsers").show();
tblQuestionRelatedUsers_render(d,"answers",selected_question)}},error:function(d){d.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(d.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+d.status,ICON_URL_NOTIFY_WRONG)}});return false});$(".qTotalLovedCount").live("click",function(a){a.preventDefault();var c=$(this).offset();a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_question=tblQuestions_getQuestion(a);selected_question!=
null&&$.ajax({url:"api/favorites/favoritedUsers/"+a,type:"GET",success:function(d){if(d!=null){$("#questionRelatedUsers").css("position","absolute");$("#questionRelatedUsers").css("top",c.top);$("#questionRelatedUsers").css("left",c.left);$("#questionRelatedUsersTitle").text("Loved");$("#questionRelatedUsers").show();tblQuestionRelatedUsers_render(d,"loved",selected_question)}},error:function(d){d.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(d.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+
":"+d.status,ICON_URL_NOTIFY_WRONG)}});return false});$(".flag").live("click",function(a){a.preventDefault();if(common_checkPOST()){a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qFlag=$(this).parents(".question_part").find(".flag");selected_qFlagSelected=$(this).parents(".question_part").find(".flagselected");selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/abuse/"+a,async:false,type:"POST",success:function(){selected_question.isQuestionAbused=
"true";selected_qFlagSelected.show();selected_qFlag.hide()},error:function(c){c.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(c.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".reask-info-do").live("click",function(a){a.preventDefault();if(common_checkPOST()){a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qFlag=$(this).parents(".question_part").find(".flag");selected_qFlagSelected=
$(this).parents(".question_part").find(".flagselected");selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/questions/reask/"+a,async:false,type:"POST",success:function(){notifyBar_display("reask succeed",ICON_URL_NOTIFY_TRUE)},error:function(c){c.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(c.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".flagselected").live("click",function(a){a.preventDefault();
if(common_checkPOST()){a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qFlag=$(this).parents(".question_part").find(".flag");selected_qFlagSelected=$(this).parents(".question_part").find(".flagselected");selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/abuse/remove/"+a,async:false,type:"POST",success:function(){selected_question.isQuestionAbused="false";selected_qFlagSelected.hide();selected_qFlag.show()},
error:function(c){c.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(c.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".love").live("click",function(a){a.preventDefault();if(common_checkPOST()){a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qLove=$(this).parents(".question_part").find(".love");selected_qLoveSelected=$(this).parents(".question_part").find(".loveselected");
selected_qLovedCount=$(this).parents(".question_part").find(".qTotalLovedCount");selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/favorites/"+a,async:false,type:"POST",success:function(){selected_question.isQuestionFaved="true";selected_question.likedCount++;selected_qLove.hide();selected_qLoveSelected.show();selected_qLovedCount.text(selected_question.likedCount+" love");common_incrementLoveQuestionCount();tblQuestions_page==PAGE_PROFILE&&profile_reflectActionsOnQuestions(QACTIONS_FAVED,
selected_question)},error:function(c){c.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(c.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".loveselected").live("click",function(a){a.preventDefault();if(common_checkPOST()){a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_qLove=$(this).parents(".question_part").find(".love");selected_qLoveSelected=$(this).parents(".question_part").find(".loveselected");
selected_qLovedCount=$(this).parents(".question_part").find(".qTotalLovedCount");selected_question=tblQuestions_getQuestion(a);selected_question!=null&&$.ajax({url:"api/favorites/remove/"+a,async:false,type:"POST",success:function(){selected_question.isQuestionFaved="false";selected_question.likedCount--;selected_qLove.show();selected_qLoveSelected.hide();selected_qLovedCount.text(selected_question.likedCount+" love");common_decrementLoveQuestionCount();tblQuestions_page==PAGE_PROFILE&&profile_reflectActionsOnQuestions(QACTIONS_UNFAVED,
selected_question)},error:function(c){c.status==HTTP_STATUS_NOT_FOUND?notifyBar_display(c.responseText,ICON_URL_NOTIFY_WRONG):notifyBar_display(ERR_MSG_WEBSERVICE+":"+c.status,ICON_URL_NOTIFY_WRONG)}})}return false});$(".share").live("click",function(a){a.preventDefault();a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();shareDlg_setContent(tblQuestions_getQuestion(a));shareDlg_display($(this),-250,0)});$(".coffeecup_sendbutton").live("click",function(a){a.preventDefault();
a=$(this).parents(".question_part").children(":first-child").children(":first-child").text();selected_question=tblQuestions_getQuestion(a);if(selected_question!=null&&selected_question.owner!=cookie_get(COOKIE_USERNAME)){a=$(this).position();coffeeDlg_setContent(selected_question.owner,cookie_get(COOKIE_USERNAME),selected_question.ownerSmallAvatarURL);coffeeDlg_show(a)}else notifyBar_display("COFFEE TO ME ?",ICON_URL_NOTIFY_WRONG)})}
function tblQuestions_answerSucceeded(b,a,c){$("#waitingIcon").hide();$("#ichoosethis_onequestion").hide();$("#statistic_onequestion").show();selected_question.answer=""+a;tblQuestions_prepareStatisticsIcon(selected_question,c);tblQuestions_clearChoiceSelection();gTable_unbindChoiceEvents();gTable_bindEventToAnsweredQuestion();tblQuestions_signSelectedChoice(a);b=tblQuestions_getAnswerOrderStatus(c,a,cookie_get(COOKIE_MARGINAL));b=b==1?"1ST":b==2?"2ND":b==3?"3RD":b+"TH";$("#answerOrder").hide();cookie_get(COOKIE_MARGINAL)==
TEXT_TRUE?$("#deltaTrend").text(b+" MOST ECCENTRIC ANSWER"):$("#deltaTrend").text(b+" MOST TRENDY ANSWER");parseInt(selected_question.totalAnswerCount);selected_question.totalAnswerCount++;selected_qTotalAnswerCount.text(selected_question.totalAnswerCount+" answered");selected_qStat.show();common_incrementAnswerQuestionCount();selected_qBody.html(common_contentProcess(selected_question.body));tblQuestions_page==PAGE_PROFILE&&profile_reflectActionsOnQuestions(QACTIONS_ANSWERED,selected_question)}
function tblQuestions_bindEventToAnsweredQuestion(){$(".answers").click(function(b){b.preventDefault()})}function tblQuestions_signSelectedChoice(b){for(i=0;i<MAX_CHOICE_COUNT;i++){var a=$("#answers_cho"+i);a.removeClass();i==b?a.addClass("cho_x_selected"):a.addClass("cho_x_notselected")}}function tblQuestions_clearChoiceSelection(){for(i=0;i<MAX_CHOICE_COUNT;i++){var b=$("#answers_cho"+i);b.removeClass();b.addClass("cho_x")}}function gTable_unbindChoiceEvents(){$(".cho_x").unbind()}
function gTable_bindEventToAnsweredQuestion(){$(".cho_x").click(function(b){b.preventDefault()})}function gTable_bindEventToNonAnsweredQuestion(){$(".cho_x").click(function(b){b.preventDefault();tblQuestions_clearChoiceSelection();selected_choice=$(this);selected_choice.addClass("cho_x_selected");$("#ichoosethis_onequestion").show()})}
function tblQuestions_defineQNodeBtnText(b){if(b==null||b.answer==null)return QNODE_BTN_INVALID;return b.answer==INDEX_OF_NOT_ANSWERED?QNODE_BTN_ANSWER:QNODE_BTN_OPENSTATS}function tblQuestions_getQuestion(b){for(i=0;i<display_questions.length;i++){var a=display_questions[i];if(a.id==b)return a}return null}function tblQuestions_removeQuestion(b){for(i=0;i<display_questions.length;i++)if(display_questions[i].id==b)break;display_questions.splice(i,1);tblQuestions_renderQuestions(tblQuestionsData)}
function tblQuestions_prepareStatisticsIcon(b,a){selected_question_choiceCount=0;var c=b.choices,d=0,e=0;for(i=0;i<10;i++)$("#answerscounter_cho"+i).text("0%");for(i=0;i<a.map.length;i++){e=a.map[i].index;if(e==QUESTION_TOTAL_ANSWERED_INDEX)d=parseInt(a.map[i].value)}for(i=0;i<a.map.length;i++){e=a.map[i].index;if(e<c.length){var f=parseInt(a.map[i].value);f=parseFloat(f*100/d).toFixed(1);if(f*10%10==0)f=parseFloat(f).toFixed();$("#answerscounter_cho"+e).text(f+"%")}}for(i=0;i<c.length;i++){d=c[i];
if(d==TEXT_NULL){$("#answers_cho"+i).hide();$("#answerscounter_cho"+i).hide()}else{$("#answers_cho"+i).show();$("#answers_cho"+i).html(common_choiceProcess(d));$("#answerscounter_cho"+i).show();selected_question_choiceCount++}}for(i=c.length;i<10;i++){$("#answers_cho"+i).hide();$("#answerscounter_cho"+i).hide()}}
function tblQuestions_getAnswerOrderStatus(b,a,c){var d=[],e=0;for(i=0;i<b.map.length;i++){var f=b.map[i].index;if(f==a)e=parseInt(b.map[i].value);else f!=QUESTION_TOTAL_ANSWERED_INDEX&&f!=84&&d.push(parseInt(b.map[i].value))}b=1;if(c==TEXT_TRUE)for(i=0;i<d.length;i++)d[i]<e&&b++;else for(i=0;i<d.length;i++)d[i]>e&&b++;return b}
function tblQuestions_prepareChoiceDistribution(b){$.ajax({url:"api/answers/distribution/"+b.id,type:"GET",contentType:"application/json; charset=utf-8",success:function(a){tblQuestions_prepareStatisticsIcon(b,a)},error:function(a){notifyBar_display(ERR_MSG_WEBSERVICE+":"+a.status,ICON_URL_NOTIFY_WRONG)}});return false}
function tblQuestions_prepareQuestionChoices(b){selected_question_choiceCount=0;b=b.choices;for(i=0;i<b.length;i++){var a=b[i];if(a==""){$("#answers_cho"+i).hide();$("#answerscounter_cho"+i).hide();$("#embed_cho"+i).hide()}else{$("#embed_cho"+i).show();$("#embed_cho"+i).data("embed_value",a);$("#embed_cho"+i).html(common_choiceBoxProcess(a));$("#answers_cho"+i).show();$("#answers_cho"+i).html(common_choiceProcess(a));$("#answerscounter_cho"+i).hide();selected_question_choiceCount++}}for(i=b.length;i<
10;i++){$("#answers_cho"+i).hide();$("#embed_cho"+i).hide();$("#answerscounter_cho"+i).hide()}}
function tblQuestions_renderQuestions(b){question_answer_process.appendTo($("#question_answer_process_container"));var a=$(window).scrollTop();$("#static_que_section").html("<div id=que_section></div>");if(b==null){b={};display_questions=null}else display_questions=$.isArray(b.question)?b.question:Array(b.question);tblQuestionsData=b;tblQuestionsData.question=display_questions;$("#que_section").render(tblQuestionsData,render_template);$(window).scrollTop(a);$(".coffeecup_sendbutton").attr("title",
"send a cup of coffee");if(selected_question!=null){b=$("div:contains("+selected_question.id+")");b!=null&&b.parents(".question_part").find(".btnAnswer").click()}};
